/* ConfigAppDoc.c generated by valac 0.16.1, the Vala compiler
 * generated from ConfigAppDoc.vala, do not modify */

/* -*- Mode: Vala; indent-tabs-mode: nil; tab-width: 2 -*- */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <common.h>
#include <gdk/gdk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>


#define DEJA_DUP_TYPE_CONFIG_WIDGET (deja_dup_config_widget_get_type ())
#define DEJA_DUP_CONFIG_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DEJA_DUP_TYPE_CONFIG_WIDGET, DejaDupConfigWidget))
#define DEJA_DUP_CONFIG_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DEJA_DUP_TYPE_CONFIG_WIDGET, DejaDupConfigWidgetClass))
#define DEJA_DUP_IS_CONFIG_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DEJA_DUP_TYPE_CONFIG_WIDGET))
#define DEJA_DUP_IS_CONFIG_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DEJA_DUP_TYPE_CONFIG_WIDGET))
#define DEJA_DUP_CONFIG_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DEJA_DUP_TYPE_CONFIG_WIDGET, DejaDupConfigWidgetClass))

typedef struct _DejaDupConfigWidget DejaDupConfigWidget;
typedef struct _DejaDupConfigWidgetClass DejaDupConfigWidgetClass;
typedef struct _DejaDupConfigWidgetPrivate DejaDupConfigWidgetPrivate;

#define DEJA_DUP_TYPE_CONFIG_APP_DOC (deja_dup_config_app_doc_get_type ())
#define DEJA_DUP_CONFIG_APP_DOC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DEJA_DUP_TYPE_CONFIG_APP_DOC, DejaDupConfigAppDoc))
#define DEJA_DUP_CONFIG_APP_DOC_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DEJA_DUP_TYPE_CONFIG_APP_DOC, DejaDupConfigAppDocClass))
#define DEJA_DUP_IS_CONFIG_APP_DOC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DEJA_DUP_TYPE_CONFIG_APP_DOC))
#define DEJA_DUP_IS_CONFIG_APP_DOC_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DEJA_DUP_TYPE_CONFIG_APP_DOC))
#define DEJA_DUP_CONFIG_APP_DOC_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DEJA_DUP_TYPE_CONFIG_APP_DOC, DejaDupConfigAppDocClass))

typedef struct _DejaDupConfigAppDoc DejaDupConfigAppDoc;
typedef struct _DejaDupConfigAppDocClass DejaDupConfigAppDocClass;
typedef struct _DejaDupConfigAppDocPrivate DejaDupConfigAppDocPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _DejaDupConfigAppDocSetFromConfigData DejaDupConfigAppDocSetFromConfigData;

#define DEJA_DUP_TYPE_CONFIG_DOC_DIALOG (deja_dup_config_doc_dialog_get_type ())
#define DEJA_DUP_CONFIG_DOC_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DEJA_DUP_TYPE_CONFIG_DOC_DIALOG, DejaDupConfigDocDialog))
#define DEJA_DUP_CONFIG_DOC_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DEJA_DUP_TYPE_CONFIG_DOC_DIALOG, DejaDupConfigDocDialogClass))
#define DEJA_DUP_IS_CONFIG_DOC_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DEJA_DUP_TYPE_CONFIG_DOC_DIALOG))
#define DEJA_DUP_IS_CONFIG_DOC_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DEJA_DUP_TYPE_CONFIG_DOC_DIALOG))
#define DEJA_DUP_CONFIG_DOC_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DEJA_DUP_TYPE_CONFIG_DOC_DIALOG, DejaDupConfigDocDialogClass))

typedef struct _DejaDupConfigDocDialog DejaDupConfigDocDialog;
typedef struct _DejaDupConfigDocDialogClass DejaDupConfigDocDialogClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _DejaDupConfigWidget {
	GtkEventBox parent_instance;
	DejaDupConfigWidgetPrivate * priv;
	gboolean syncing;
	DejaDupSimpleSettings* settings;
	GList* all_settings;
};

struct _DejaDupConfigWidgetClass {
	GtkEventBoxClass parent_class;
	void (*set_from_config) (DejaDupConfigWidget* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*set_from_config_finish) (DejaDupConfigWidget* self, GAsyncResult* _res_);
};

struct _DejaDupConfigAppDoc {
	DejaDupConfigWidget parent_instance;
	DejaDupConfigAppDocPrivate * priv;
	GtkHBox* hbox;
	GtkImage* icon;
	GtkLabel* label;
	GtkLabel* status;
	GtkArrow* next;
	GtkEventBox* event_box;
	gboolean user_driven;
};

struct _DejaDupConfigAppDocClass {
	DejaDupConfigWidgetClass parent_class;
	void (*fill_box) (DejaDupConfigAppDoc* self);
};

struct _DejaDupConfigAppDocSetFromConfigData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	DejaDupConfigAppDoc* self;
};


static gpointer deja_dup_config_app_doc_parent_class = NULL;

GType deja_dup_config_widget_get_type (void) G_GNUC_CONST;
GType deja_dup_config_app_doc_get_type (void) G_GNUC_CONST;
enum  {
	DEJA_DUP_CONFIG_APP_DOC_DUMMY_PROPERTY
};
DejaDupConfigAppDoc* deja_dup_config_app_doc_new (void);
DejaDupConfigAppDoc* deja_dup_config_app_doc_construct (GType object_type);
DejaDupConfigWidget* deja_dup_config_widget_construct (GType object_type);
void deja_dup_config_app_doc_fill_box (DejaDupConfigAppDoc* self);
static void deja_dup_config_app_doc_real_fill_box (DejaDupConfigAppDoc* self);
static void deja_dup_config_app_doc_real_set_from_config_data_free (gpointer _data);
static void deja_dup_config_app_doc_real_set_from_config (DejaDupConfigWidget* base, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean deja_dup_config_app_doc_real_set_from_config_co (DejaDupConfigAppDocSetFromConfigData* _data_);
static gboolean deja_dup_config_app_doc_on_click (DejaDupConfigAppDoc* self, GdkEventButton* event);
DejaDupConfigDocDialog* deja_dup_config_doc_dialog_new (void);
DejaDupConfigDocDialog* deja_dup_config_doc_dialog_construct (GType object_type);
GType deja_dup_config_doc_dialog_get_type (void) G_GNUC_CONST;
void deja_dup_config_app_doc_on_doc_toggled (DejaDupConfigAppDoc* self, gboolean sensitivity);
static void _deja_dup_config_app_doc_on_doc_toggled_deja_dup_config_doc_dialog_doc_toggled (DejaDupConfigDocDialog* _sender, gboolean sensitivity, gpointer self);
static GObject * deja_dup_config_app_doc_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static gboolean _deja_dup_config_app_doc_on_click_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
void deja_dup_config_widget_set_from_config (DejaDupConfigWidget* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
void deja_dup_config_widget_set_from_config_finish (DejaDupConfigWidget* self, GAsyncResult* _res_);
static void deja_dup_config_app_doc_finalize (GObject* obj);


DejaDupConfigAppDoc* deja_dup_config_app_doc_construct (GType object_type) {
	DejaDupConfigAppDoc * self = NULL;
	self = (DejaDupConfigAppDoc*) deja_dup_config_widget_construct (object_type);
	return self;
}


DejaDupConfigAppDoc* deja_dup_config_app_doc_new (void) {
	return deja_dup_config_app_doc_construct (DEJA_DUP_TYPE_CONFIG_APP_DOC);
}


static void deja_dup_config_app_doc_real_fill_box (DejaDupConfigAppDoc* self) {
	GtkHBox* _tmp0_;
	GtkImage* _tmp1_;
	GtkHBox* _tmp2_;
	GtkLabel* _tmp3_;
	GtkHBox* _tmp4_;
	GtkEventBox* _tmp5_;
	GtkHBox* _tmp6_;
	GtkLabel* _tmp7_;
	_tmp0_ = self->hbox;
	_tmp1_ = self->icon;
	gtk_box_pack_start ((GtkBox*) _tmp0_, (GtkWidget*) _tmp1_, FALSE, FALSE, (guint) 0);
	_tmp2_ = self->hbox;
	_tmp3_ = self->label;
	gtk_box_pack_start ((GtkBox*) _tmp2_, (GtkWidget*) _tmp3_, FALSE, FALSE, (guint) 0);
	_tmp4_ = self->hbox;
	_tmp5_ = self->event_box;
	gtk_box_pack_end ((GtkBox*) _tmp4_, (GtkWidget*) _tmp5_, FALSE, FALSE, (guint) 0);
	_tmp6_ = self->hbox;
	_tmp7_ = self->status;
	gtk_box_pack_end ((GtkBox*) _tmp6_, (GtkWidget*) _tmp7_, FALSE, FALSE, (guint) 0);
}


void deja_dup_config_app_doc_fill_box (DejaDupConfigAppDoc* self) {
	g_return_if_fail (self != NULL);
	DEJA_DUP_CONFIG_APP_DOC_GET_CLASS (self)->fill_box (self);
}


static void deja_dup_config_app_doc_real_set_from_config_data_free (gpointer _data) {
	DejaDupConfigAppDocSetFromConfigData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (DejaDupConfigAppDocSetFromConfigData, _data_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void deja_dup_config_app_doc_real_set_from_config (DejaDupConfigWidget* base, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	DejaDupConfigAppDoc * self;
	DejaDupConfigAppDocSetFromConfigData* _data_;
	DejaDupConfigAppDoc* _tmp0_;
	self = (DejaDupConfigAppDoc*) base;
	_data_ = g_slice_new0 (DejaDupConfigAppDocSetFromConfigData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, deja_dup_config_app_doc_real_set_from_config);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, deja_dup_config_app_doc_real_set_from_config_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	deja_dup_config_app_doc_real_set_from_config_co (_data_);
}


static void deja_dup_config_app_doc_real_set_from_config_finish (DejaDupConfigWidget* base, GAsyncResult* _res_) {
	DejaDupConfigAppDocSetFromConfigData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static gboolean deja_dup_config_app_doc_real_set_from_config_co (DejaDupConfigAppDocSetFromConfigData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void _deja_dup_config_app_doc_on_doc_toggled_deja_dup_config_doc_dialog_doc_toggled (DejaDupConfigDocDialog* _sender, gboolean sensitivity, gpointer self) {
	deja_dup_config_app_doc_on_doc_toggled (self, sensitivity);
}


static gboolean deja_dup_config_app_doc_on_click (DejaDupConfigAppDoc* self, GdkEventButton* event) {
	gboolean result = FALSE;
	DejaDupConfigDocDialog* _tmp0_;
	DejaDupConfigDocDialog* _tmp1_;
	DejaDupConfigDocDialog* docdlg;
	GtkWidget* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = deja_dup_config_doc_dialog_new ();
	_tmp1_ = g_object_ref_sink (_tmp0_);
	docdlg = _tmp1_;
	_tmp2_ = gtk_widget_get_ancestor ((GtkWidget*) self, GTK_TYPE_WINDOW);
	gtk_window_set_transient_for ((GtkWindow*) docdlg, GTK_IS_WINDOW (_tmp2_) ? ((GtkWindow*) _tmp2_) : NULL);
	g_signal_connect_object (docdlg, "doc-toggled", (GCallback) _deja_dup_config_app_doc_on_doc_toggled_deja_dup_config_doc_dialog_doc_toggled, self, 0);
	gtk_widget_show_all ((GtkWidget*) docdlg);
	result = TRUE;
	_g_object_unref0 (docdlg);
	return result;
}


void deja_dup_config_app_doc_on_doc_toggled (DejaDupConfigAppDoc* self, gboolean sensitivity) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = sensitivity;
	if (_tmp0_) {
		GtkLabel* _tmp1_;
		const gchar* _tmp2_ = NULL;
		_tmp1_ = self->status;
		_tmp2_ = _ ("On");
		gtk_label_set_text (_tmp1_, _tmp2_);
	} else {
		GtkLabel* _tmp3_;
		const gchar* _tmp4_ = NULL;
		_tmp3_ = self->status;
		_tmp4_ = _ ("Off");
		gtk_label_set_text (_tmp3_, _tmp4_);
	}
}


static gboolean _deja_dup_config_app_doc_on_click_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = deja_dup_config_app_doc_on_click (self, event);
	return result;
}


static GObject * deja_dup_config_app_doc_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	DejaDupConfigAppDoc * self;
	GtkAlignment* align = NULL;
	GtkAlignment* _tmp0_;
	GtkAlignment* _tmp1_;
	GtkAlignment* _tmp2_;
	GtkAlignment* _tmp3_;
	GtkAlignment* _tmp4_;
	GtkHBox* _tmp5_;
	GtkHBox* _tmp6_;
	GtkAlignment* _tmp7_;
	GtkHBox* _tmp8_;
	GtkImage* _tmp9_;
	GtkImage* _tmp10_;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_;
	GtkLabel* _tmp14_;
	GtkLabel* _tmp15_;
	GtkLabel* _tmp16_;
	DejaDupSimpleSettings* _tmp17_ = NULL;
	DejaDupSimpleSettings* settings;
	DejaDupSimpleSettings* _tmp18_;
	gboolean _tmp19_ = FALSE;
	gboolean val;
	gboolean _tmp20_;
	GtkLabel* _tmp31_;
	GtkArrow* _tmp32_;
	GtkArrow* _tmp33_;
	GtkEventBox* _tmp34_;
	GtkEventBox* _tmp35_;
	GtkEventBox* _tmp36_;
	GtkArrow* _tmp37_;
	GtkEventBox* _tmp38_;
	GtkEventBox* _tmp39_;
	GtkEventBox* _tmp40_;
	GtkEventBox* _tmp41_;
	parent_class = G_OBJECT_CLASS (deja_dup_config_app_doc_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = DEJA_DUP_CONFIG_APP_DOC (obj);
	_tmp0_ = (GtkAlignment*) gtk_alignment_new (0.5f, 0.5f, 1.0f, 1.0f);
	_tmp1_ = g_object_ref_sink (_tmp0_);
	_g_object_unref0 (align);
	align = _tmp1_;
	_tmp2_ = align;
	g_object_set (_tmp2_, "left-padding", (guint) 5, NULL);
	_tmp3_ = align;
	g_object_set (_tmp3_, "right-padding", (guint) 5, NULL);
	_tmp4_ = align;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp4_);
	_tmp5_ = (GtkHBox*) gtk_hbox_new (FALSE, 5);
	_tmp6_ = g_object_ref_sink (_tmp5_);
	_g_object_unref0 (self->hbox);
	self->hbox = _tmp6_;
	_tmp7_ = align;
	_tmp8_ = self->hbox;
	gtk_container_add ((GtkContainer*) _tmp7_, (GtkWidget*) _tmp8_);
	_tmp9_ = (GtkImage*) gtk_image_new_from_icon_name ("gnome-documents", GTK_ICON_SIZE_BUTTON);
	_tmp10_ = g_object_ref_sink (_tmp9_);
	_g_object_unref0 (self->icon);
	self->icon = _tmp10_;
	_tmp11_ = _ ("Documents and Data");
	_tmp12_ = g_strdup_printf ("%s", _tmp11_);
	_tmp13_ = _tmp12_;
	_tmp14_ = (GtkLabel*) gtk_label_new (_tmp13_);
	_tmp15_ = g_object_ref_sink (_tmp14_);
	_g_object_unref0 (self->label);
	self->label = _tmp15_;
	_g_free0 (_tmp13_);
	_tmp16_ = self->label;
	g_object_set ((GObject*) _tmp16_, "use-markup", TRUE, "xalign", 0.0f, NULL);
	_tmp17_ = deja_dup_get_settings (DEJA_DUP_APPS_ROOT ".document-data");
	settings = _tmp17_;
	_tmp18_ = settings;
	_tmp19_ = g_settings_get_boolean ((GSettings*) _tmp18_, DEJA_DUP_BACKUP_KEY);
	val = _tmp19_;
	_tmp20_ = val;
	if (_tmp20_) {
		const gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		gchar* _tmp23_;
		GtkLabel* _tmp24_;
		GtkLabel* _tmp25_;
		_tmp21_ = _ ("On");
		_tmp22_ = g_strdup_printf ("%s", _tmp21_);
		_tmp23_ = _tmp22_;
		_tmp24_ = (GtkLabel*) gtk_label_new (_tmp23_);
		_tmp25_ = g_object_ref_sink (_tmp24_);
		_g_object_unref0 (self->status);
		self->status = _tmp25_;
		_g_free0 (_tmp23_);
	} else {
		const gchar* _tmp26_ = NULL;
		gchar* _tmp27_ = NULL;
		gchar* _tmp28_;
		GtkLabel* _tmp29_;
		GtkLabel* _tmp30_;
		_tmp26_ = _ ("Off");
		_tmp27_ = g_strdup_printf ("%s", _tmp26_);
		_tmp28_ = _tmp27_;
		_tmp29_ = (GtkLabel*) gtk_label_new (_tmp28_);
		_tmp30_ = g_object_ref_sink (_tmp29_);
		_g_object_unref0 (self->status);
		self->status = _tmp30_;
		_g_free0 (_tmp28_);
	}
	_tmp31_ = self->status;
	g_object_set ((GObject*) _tmp31_, "use-markup", TRUE, "xalign", 0.0f, NULL);
	_tmp32_ = (GtkArrow*) gtk_arrow_new (GTK_ARROW_RIGHT, GTK_SHADOW_ETCHED_IN);
	_tmp33_ = g_object_ref_sink (_tmp32_);
	_g_object_unref0 (self->next);
	self->next = _tmp33_;
	_tmp34_ = (GtkEventBox*) gtk_event_box_new ();
	_tmp35_ = g_object_ref_sink (_tmp34_);
	_g_object_unref0 (self->event_box);
	self->event_box = _tmp35_;
	_tmp36_ = self->event_box;
	_tmp37_ = self->next;
	gtk_container_add ((GtkContainer*) _tmp36_, (GtkWidget*) _tmp37_);
	_tmp38_ = self->event_box;
	gtk_widget_set_size_request ((GtkWidget*) _tmp38_, 30, 30);
	_tmp39_ = self->event_box;
	gtk_widget_add_events ((GtkWidget*) _tmp39_, (gint) GDK_BUTTON_PRESS_MASK);
	_tmp40_ = self->event_box;
	g_signal_connect_object ((GtkWidget*) _tmp40_, "button-press-event", (GCallback) _deja_dup_config_app_doc_on_click_gtk_widget_button_press_event, self, 0);
	deja_dup_config_app_doc_fill_box (self);
	deja_dup_config_widget_set_from_config ((DejaDupConfigWidget*) self, NULL, NULL);
	_tmp41_ = self->event_box;
	gtk_widget_show ((GtkWidget*) _tmp41_);
	_g_object_unref0 (settings);
	_g_object_unref0 (align);
	return obj;
}


static void deja_dup_config_app_doc_class_init (DejaDupConfigAppDocClass * klass) {
	deja_dup_config_app_doc_parent_class = g_type_class_peek_parent (klass);
	DEJA_DUP_CONFIG_APP_DOC_CLASS (klass)->fill_box = deja_dup_config_app_doc_real_fill_box;
	DEJA_DUP_CONFIG_WIDGET_CLASS (klass)->set_from_config = deja_dup_config_app_doc_real_set_from_config;
	DEJA_DUP_CONFIG_WIDGET_CLASS (klass)->set_from_config_finish = deja_dup_config_app_doc_real_set_from_config_finish;
	G_OBJECT_CLASS (klass)->constructor = deja_dup_config_app_doc_constructor;
	G_OBJECT_CLASS (klass)->finalize = deja_dup_config_app_doc_finalize;
}


static void deja_dup_config_app_doc_instance_init (DejaDupConfigAppDoc * self) {
	self->user_driven = TRUE;
}


static void deja_dup_config_app_doc_finalize (GObject* obj) {
	DejaDupConfigAppDoc * self;
	self = DEJA_DUP_CONFIG_APP_DOC (obj);
	_g_object_unref0 (self->hbox);
	_g_object_unref0 (self->icon);
	_g_object_unref0 (self->label);
	_g_object_unref0 (self->status);
	_g_object_unref0 (self->next);
	_g_object_unref0 (self->event_box);
	G_OBJECT_CLASS (deja_dup_config_app_doc_parent_class)->finalize (obj);
}


GType deja_dup_config_app_doc_get_type (void) {
	static volatile gsize deja_dup_config_app_doc_type_id__volatile = 0;
	if (g_once_init_enter (&deja_dup_config_app_doc_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DejaDupConfigAppDocClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) deja_dup_config_app_doc_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DejaDupConfigAppDoc), 0, (GInstanceInitFunc) deja_dup_config_app_doc_instance_init, NULL };
		GType deja_dup_config_app_doc_type_id;
		deja_dup_config_app_doc_type_id = g_type_register_static (DEJA_DUP_TYPE_CONFIG_WIDGET, "DejaDupConfigAppDoc", &g_define_type_info, 0);
		g_once_init_leave (&deja_dup_config_app_doc_type_id__volatile, deja_dup_config_app_doc_type_id);
	}
	return deja_dup_config_app_doc_type_id__volatile;
}



