/* ConfigLabel.c generated by valac 0.16.1, the Vala compiler
 * generated from ConfigLabel.vala, do not modify */

/* -*- Mode: Vala; indent-tabs-mode: nil; tab-width: 2 -*- */
/*
    This file is part of Déjà Dup.
    For copyright information, see AUTHORS.

    Déjà Dup is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Déjà Dup is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <common.h>
#include <stdlib.h>
#include <string.h>


#define DEJA_DUP_TYPE_CONFIG_WIDGET (deja_dup_config_widget_get_type ())
#define DEJA_DUP_CONFIG_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DEJA_DUP_TYPE_CONFIG_WIDGET, DejaDupConfigWidget))
#define DEJA_DUP_CONFIG_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DEJA_DUP_TYPE_CONFIG_WIDGET, DejaDupConfigWidgetClass))
#define DEJA_DUP_IS_CONFIG_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DEJA_DUP_TYPE_CONFIG_WIDGET))
#define DEJA_DUP_IS_CONFIG_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DEJA_DUP_TYPE_CONFIG_WIDGET))
#define DEJA_DUP_CONFIG_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DEJA_DUP_TYPE_CONFIG_WIDGET, DejaDupConfigWidgetClass))

typedef struct _DejaDupConfigWidget DejaDupConfigWidget;
typedef struct _DejaDupConfigWidgetClass DejaDupConfigWidgetClass;
typedef struct _DejaDupConfigWidgetPrivate DejaDupConfigWidgetPrivate;

#define DEJA_DUP_TYPE_CONFIG_LABEL (deja_dup_config_label_get_type ())
#define DEJA_DUP_CONFIG_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DEJA_DUP_TYPE_CONFIG_LABEL, DejaDupConfigLabel))
#define DEJA_DUP_CONFIG_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DEJA_DUP_TYPE_CONFIG_LABEL, DejaDupConfigLabelClass))
#define DEJA_DUP_IS_CONFIG_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DEJA_DUP_TYPE_CONFIG_LABEL))
#define DEJA_DUP_IS_CONFIG_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DEJA_DUP_TYPE_CONFIG_LABEL))
#define DEJA_DUP_CONFIG_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DEJA_DUP_TYPE_CONFIG_LABEL, DejaDupConfigLabelClass))

typedef struct _DejaDupConfigLabel DejaDupConfigLabel;
typedef struct _DejaDupConfigLabelClass DejaDupConfigLabelClass;
typedef struct _DejaDupConfigLabelPrivate DejaDupConfigLabelPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _DejaDupConfigLabelSetFromConfigData DejaDupConfigLabelSetFromConfigData;

struct _DejaDupConfigWidget {
	GtkEventBox parent_instance;
	DejaDupConfigWidgetPrivate * priv;
	gboolean syncing;
	DejaDupSimpleSettings* settings;
	GList* all_settings;
};

struct _DejaDupConfigWidgetClass {
	GtkEventBoxClass parent_class;
	void (*set_from_config) (DejaDupConfigWidget* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*set_from_config_finish) (DejaDupConfigWidget* self, GAsyncResult* _res_);
};

struct _DejaDupConfigLabel {
	DejaDupConfigWidget parent_instance;
	DejaDupConfigLabelPrivate * priv;
	GtkGrid* box;
	GtkLabel* label;
};

struct _DejaDupConfigLabelClass {
	DejaDupConfigWidgetClass parent_class;
	void (*fill_box) (DejaDupConfigLabel* self);
};

struct _DejaDupConfigLabelSetFromConfigData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	DejaDupConfigLabel* self;
	GtkLabel* _tmp0_;
	DejaDupSimpleSettings* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
};


static gpointer deja_dup_config_label_parent_class = NULL;

GType deja_dup_config_widget_get_type (void) G_GNUC_CONST;
GType deja_dup_config_label_get_type (void) G_GNUC_CONST;
enum  {
	DEJA_DUP_CONFIG_LABEL_DUMMY_PROPERTY
};
DejaDupConfigLabel* deja_dup_config_label_new (const gchar* key, const gchar* ns);
DejaDupConfigLabel* deja_dup_config_label_construct (GType object_type, const gchar* key, const gchar* ns);
void deja_dup_config_label_fill_box (DejaDupConfigLabel* self);
static void deja_dup_config_label_real_fill_box (DejaDupConfigLabel* self);
static void deja_dup_config_label_real_set_from_config_data_free (gpointer _data);
static void deja_dup_config_label_real_set_from_config (DejaDupConfigWidget* base, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean deja_dup_config_label_real_set_from_config_co (DejaDupConfigLabelSetFromConfigData* _data_);
const gchar* deja_dup_config_widget_get_key (DejaDupConfigWidget* self);
static GObject * deja_dup_config_label_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
void deja_dup_config_widget_set_from_config (DejaDupConfigWidget* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
void deja_dup_config_widget_set_from_config_finish (DejaDupConfigWidget* self, GAsyncResult* _res_);
static void deja_dup_config_label_finalize (GObject* obj);


DejaDupConfigLabel* deja_dup_config_label_construct (GType object_type, const gchar* key, const gchar* ns) {
	DejaDupConfigLabel * self = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	g_return_val_if_fail (ns != NULL, NULL);
	_tmp0_ = key;
	_tmp1_ = ns;
	self = (DejaDupConfigLabel*) g_object_new (object_type, "key", _tmp0_, "ns", _tmp1_, NULL);
	return self;
}


DejaDupConfigLabel* deja_dup_config_label_new (const gchar* key, const gchar* ns) {
	return deja_dup_config_label_construct (DEJA_DUP_TYPE_CONFIG_LABEL, key, ns);
}


static void deja_dup_config_label_real_fill_box (DejaDupConfigLabel* self) {
}


void deja_dup_config_label_fill_box (DejaDupConfigLabel* self) {
	g_return_if_fail (self != NULL);
	DEJA_DUP_CONFIG_LABEL_GET_CLASS (self)->fill_box (self);
}


static void deja_dup_config_label_real_set_from_config_data_free (gpointer _data) {
	DejaDupConfigLabelSetFromConfigData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (DejaDupConfigLabelSetFromConfigData, _data_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void deja_dup_config_label_real_set_from_config (DejaDupConfigWidget* base, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	DejaDupConfigLabel * self;
	DejaDupConfigLabelSetFromConfigData* _data_;
	DejaDupConfigLabel* _tmp0_;
	self = (DejaDupConfigLabel*) base;
	_data_ = g_slice_new0 (DejaDupConfigLabelSetFromConfigData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, deja_dup_config_label_real_set_from_config);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, deja_dup_config_label_real_set_from_config_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	deja_dup_config_label_real_set_from_config_co (_data_);
}


static void deja_dup_config_label_real_set_from_config_finish (DejaDupConfigWidget* base, GAsyncResult* _res_) {
	DejaDupConfigLabelSetFromConfigData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static gboolean deja_dup_config_label_real_set_from_config_co (DejaDupConfigLabelSetFromConfigData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->label;
	_data_->_tmp1_ = ((DejaDupConfigWidget*) _data_->self)->settings;
	_data_->_tmp2_ = deja_dup_config_widget_get_key ((DejaDupConfigWidget*) _data_->self);
	_data_->_tmp3_ = _data_->_tmp2_;
	_data_->_tmp4_ = NULL;
	_data_->_tmp4_ = g_settings_get_string ((GSettings*) _data_->_tmp1_, _data_->_tmp3_);
	_data_->_tmp5_ = _data_->_tmp4_;
	gtk_label_set_label (_data_->_tmp0_, _data_->_tmp5_);
	_g_free0 (_data_->_tmp5_);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static GObject * deja_dup_config_label_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	DejaDupConfigLabel * self;
	GtkLabel* _tmp0_;
	GtkLabel* _tmp1_;
	GtkLabel* _tmp2_;
	GtkLabel* _tmp3_;
	GtkLabel* _tmp4_;
	parent_class = G_OBJECT_CLASS (deja_dup_config_label_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = DEJA_DUP_CONFIG_LABEL (obj);
	_tmp0_ = (GtkLabel*) gtk_label_new ("");
	_tmp1_ = g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->label);
	self->label = _tmp1_;
	_tmp2_ = self->label;
	gtk_widget_set_size_request ((GtkWidget*) _tmp2_, 430, -1);
	_tmp3_ = self->label;
	g_object_set ((GtkMisc*) _tmp3_, "xalign", 0.0f, NULL);
	_tmp4_ = self->label;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp4_);
	deja_dup_config_widget_set_from_config ((DejaDupConfigWidget*) self, NULL, NULL);
	return obj;
}


static void deja_dup_config_label_class_init (DejaDupConfigLabelClass * klass) {
	deja_dup_config_label_parent_class = g_type_class_peek_parent (klass);
	DEJA_DUP_CONFIG_LABEL_CLASS (klass)->fill_box = deja_dup_config_label_real_fill_box;
	DEJA_DUP_CONFIG_WIDGET_CLASS (klass)->set_from_config = deja_dup_config_label_real_set_from_config;
	DEJA_DUP_CONFIG_WIDGET_CLASS (klass)->set_from_config_finish = deja_dup_config_label_real_set_from_config_finish;
	G_OBJECT_CLASS (klass)->constructor = deja_dup_config_label_constructor;
	G_OBJECT_CLASS (klass)->finalize = deja_dup_config_label_finalize;
}


static void deja_dup_config_label_instance_init (DejaDupConfigLabel * self) {
}


static void deja_dup_config_label_finalize (GObject* obj) {
	DejaDupConfigLabel * self;
	self = DEJA_DUP_CONFIG_LABEL (obj);
	_g_object_unref0 (self->box);
	_g_object_unref0 (self->label);
	G_OBJECT_CLASS (deja_dup_config_label_parent_class)->finalize (obj);
}


GType deja_dup_config_label_get_type (void) {
	static volatile gsize deja_dup_config_label_type_id__volatile = 0;
	if (g_once_init_enter (&deja_dup_config_label_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DejaDupConfigLabelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) deja_dup_config_label_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DejaDupConfigLabel), 0, (GInstanceInitFunc) deja_dup_config_label_instance_init, NULL };
		GType deja_dup_config_label_type_id;
		deja_dup_config_label_type_id = g_type_register_static (DEJA_DUP_TYPE_CONFIG_WIDGET, "DejaDupConfigLabel", &g_define_type_info, 0);
		g_once_init_leave (&deja_dup_config_label_type_id__volatile, deja_dup_config_label_type_id);
	}
	return deja_dup_config_label_type_id__volatile;
}



