/* AppsPlugin.c generated by valac 0.16.1, the Vala compiler
 * generated from AppsPlugin.vala, do not modify */

/* -*- Mode: Vala; indent-tabs-mode: nil; tab-width: 2 -*- */
/*
    This file is part of Déjà Dup.
    For copyright information, see AUTHORS.

    Déjà Dup is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Déjà Dup is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <glib.h>
#include <glib-object.h>
#include <libpeas/peas.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_APPS_PLUGIN (apps_plugin_get_type ())
#define APPS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_APPS_PLUGIN, AppsPlugin))
#define APPS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_APPS_PLUGIN, AppsPluginClass))
#define IS_APPS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_APPS_PLUGIN))
#define IS_APPS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_APPS_PLUGIN))
#define APPS_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_APPS_PLUGIN, AppsPluginClass))

typedef struct _AppsPlugin AppsPlugin;
typedef struct _AppsPluginClass AppsPluginClass;
typedef struct _AppsPluginPrivate AppsPluginPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _AppsPlugin {
	PeasExtensionBase parent_instance;
	AppsPluginPrivate * priv;
};

struct _AppsPluginClass {
	PeasExtensionBaseClass parent_class;
	void (*activate) (AppsPlugin* self);
	void (*deactivate) (AppsPlugin* self);
	void (*update_state) (AppsPlugin* self);
};

struct _AppsPluginPrivate {
	GObject* _object;
};


static gpointer apps_plugin_parent_class = NULL;
static PeasActivatableInterface* apps_plugin_peas_activatable_parent_iface = NULL;
static GType apps_plugin_type_id = 0;

GType apps_plugin_get_type (void) G_GNUC_CONST;
GType apps_plugin_register_type (GTypeModule * module);
#define APPS_PLUGIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_APPS_PLUGIN, AppsPluginPrivate))
enum  {
	APPS_PLUGIN_DUMMY_PROPERTY,
	APPS_PLUGIN_OBJECT
};
void apps_plugin_activate (AppsPlugin* self);
static void apps_plugin_real_activate (AppsPlugin* self);
void apps_plugin_deactivate (AppsPlugin* self);
static void apps_plugin_real_deactivate (AppsPlugin* self);
void apps_plugin_update_state (AppsPlugin* self);
static void apps_plugin_real_update_state (AppsPlugin* self);
AppsPlugin* apps_plugin_new (void);
AppsPlugin* apps_plugin_construct (GType object_type);
static GObject * apps_plugin_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void apps_plugin_finalize (GObject* obj);
static void _vala_apps_plugin_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_apps_plugin_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
void peas_register_types (GTypeModule* module);


static void apps_plugin_real_activate (AppsPlugin* self) {
}


void apps_plugin_activate (AppsPlugin* self) {
	g_return_if_fail (self != NULL);
	APPS_PLUGIN_GET_CLASS (self)->activate (self);
}


static void apps_plugin_real_deactivate (AppsPlugin* self) {
}


void apps_plugin_deactivate (AppsPlugin* self) {
	g_return_if_fail (self != NULL);
	APPS_PLUGIN_GET_CLASS (self)->deactivate (self);
}


static void apps_plugin_real_update_state (AppsPlugin* self) {
}


void apps_plugin_update_state (AppsPlugin* self) {
	g_return_if_fail (self != NULL);
	APPS_PLUGIN_GET_CLASS (self)->update_state (self);
}


AppsPlugin* apps_plugin_construct (GType object_type) {
	AppsPlugin * self = NULL;
	self = (AppsPlugin*) g_object_new (object_type, NULL);
	return self;
}


AppsPlugin* apps_plugin_new (void) {
	return apps_plugin_construct (TYPE_APPS_PLUGIN);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static GObject* apps_plugin_real_get_object (PeasActivatable* base) {
	GObject* result;
	AppsPlugin* self;
	GObject* _tmp0_;
	GObject* _tmp1_;
	self = (AppsPlugin*) base;
	_tmp0_ = self->priv->_object;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


static void apps_plugin_real_set_object (PeasActivatable* base, GObject* value) {
	AppsPlugin* self;
	GObject* _tmp0_;
	GObject* _tmp1_;
	self = (AppsPlugin*) base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_object);
	self->priv->_object = _tmp1_;
	g_object_notify ((GObject *) self, "object");
}


static GObject * apps_plugin_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	AppsPlugin * self;
	gchar* output = NULL;
	parent_class = G_OBJECT_CLASS (apps_plugin_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = APPS_PLUGIN (obj);
	_g_free0 (output);
	return obj;
}


static void apps_plugin_class_init (AppsPluginClass * klass) {
	apps_plugin_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (AppsPluginPrivate));
	APPS_PLUGIN_CLASS (klass)->activate = apps_plugin_real_activate;
	APPS_PLUGIN_CLASS (klass)->deactivate = apps_plugin_real_deactivate;
	APPS_PLUGIN_CLASS (klass)->update_state = apps_plugin_real_update_state;
	G_OBJECT_CLASS (klass)->get_property = _vala_apps_plugin_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_apps_plugin_set_property;
	G_OBJECT_CLASS (klass)->constructor = apps_plugin_constructor;
	G_OBJECT_CLASS (klass)->finalize = apps_plugin_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), APPS_PLUGIN_OBJECT, g_param_spec_object ("object", "object", "object", G_TYPE_OBJECT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
}


static void apps_plugin_peas_activatable_interface_init (PeasActivatableInterface * iface) {
	apps_plugin_peas_activatable_parent_iface = g_type_interface_peek_parent (iface);
	iface->activate = (void (*)(PeasActivatable*)) apps_plugin_activate;
	iface->deactivate = (void (*)(PeasActivatable*)) apps_plugin_deactivate;
	iface->update_state = (void (*)(PeasActivatable*)) apps_plugin_update_state;
}


static void apps_plugin_instance_init (AppsPlugin * self) {
	self->priv = APPS_PLUGIN_GET_PRIVATE (self);
}


static void apps_plugin_finalize (GObject* obj) {
	AppsPlugin * self;
	self = APPS_PLUGIN (obj);
	_g_object_unref0 (self->priv->_object);
	G_OBJECT_CLASS (apps_plugin_parent_class)->finalize (obj);
}


GType apps_plugin_get_type (void) {
	return apps_plugin_type_id;
}


GType apps_plugin_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (AppsPluginClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) apps_plugin_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppsPlugin), 0, (GInstanceInitFunc) apps_plugin_instance_init, NULL };
	static const GInterfaceInfo peas_activatable_info = { (GInterfaceInitFunc) apps_plugin_peas_activatable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	apps_plugin_type_id = g_type_module_register_type (module, peas_extension_base_get_type (), "AppsPlugin", &g_define_type_info, 0);
	g_type_module_add_interface (module, apps_plugin_type_id, peas_activatable_get_type (), &peas_activatable_info);
	return apps_plugin_type_id;
}


static void _vala_apps_plugin_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	AppsPlugin * self;
	self = APPS_PLUGIN (object);
	switch (property_id) {
		case APPS_PLUGIN_OBJECT:
		g_value_take_object (value, apps_plugin_real_get_object ((PeasActivatable*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_apps_plugin_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	AppsPlugin * self;
	self = APPS_PLUGIN (object);
	switch (property_id) {
		case APPS_PLUGIN_OBJECT:
		apps_plugin_real_set_object ((PeasActivatable*) self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


void peas_register_types (GTypeModule* module) {
	GTypeModule* _tmp0_;
	PeasObjectModule* _tmp1_;
	PeasObjectModule* objmodule;
	g_return_if_fail (module != NULL);
	apps_plugin_register_type (module);
	_tmp0_ = module;
	_tmp1_ = _g_object_ref0 (PEAS_IS_OBJECT_MODULE (_tmp0_) ? ((PeasObjectModule*) _tmp0_) : NULL);
	objmodule = _tmp1_;
	peas_object_module_register_extension_type (objmodule, peas_activatable_get_type (), TYPE_APPS_PLUGIN);
	_g_object_unref0 (objmodule);
}



