/* AssistantRestore.c generated by valac 0.16.1, the Vala compiler
 * generated from AssistantRestore.vala, do not modify */

/* -*- Mode: Vala; indent-tabs-mode: nil; tab-width: 2 -*- */
/*
    This file is part of Déjà Dup.
    For copyright information, see AUTHORS.

    Déjà Dup is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Déjà Dup is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <common.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <widgets.h>
#include <glib/gi18n-lib.h>
#include <time.h>
#include <config.h>
#include <float.h>
#include <math.h>


#define TYPE_ASSISTANT (assistant_get_type ())
#define ASSISTANT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ASSISTANT, Assistant))
#define ASSISTANT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ASSISTANT, AssistantClass))
#define IS_ASSISTANT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ASSISTANT))
#define IS_ASSISTANT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ASSISTANT))
#define ASSISTANT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ASSISTANT, AssistantClass))

typedef struct _Assistant Assistant;
typedef struct _AssistantClass AssistantClass;
typedef struct _AssistantPrivate AssistantPrivate;

#define ASSISTANT_TYPE_PAGE_INFO (assistant_page_info_get_type ())
#define ASSISTANT_PAGE_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ASSISTANT_TYPE_PAGE_INFO, AssistantPageInfo))
#define ASSISTANT_PAGE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ASSISTANT_TYPE_PAGE_INFO, AssistantPageInfoClass))
#define ASSISTANT_IS_PAGE_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ASSISTANT_TYPE_PAGE_INFO))
#define ASSISTANT_IS_PAGE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ASSISTANT_TYPE_PAGE_INFO))
#define ASSISTANT_PAGE_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ASSISTANT_TYPE_PAGE_INFO, AssistantPageInfoClass))

typedef struct _AssistantPageInfo AssistantPageInfo;
typedef struct _AssistantPageInfoClass AssistantPageInfoClass;

#define TYPE_ASSISTANT_OPERATION (assistant_operation_get_type ())
#define ASSISTANT_OPERATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ASSISTANT_OPERATION, AssistantOperation))
#define ASSISTANT_OPERATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ASSISTANT_OPERATION, AssistantOperationClass))
#define IS_ASSISTANT_OPERATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ASSISTANT_OPERATION))
#define IS_ASSISTANT_OPERATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ASSISTANT_OPERATION))
#define ASSISTANT_OPERATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ASSISTANT_OPERATION, AssistantOperationClass))

typedef struct _AssistantOperation AssistantOperation;
typedef struct _AssistantOperationClass AssistantOperationClass;
typedef struct _AssistantOperationPrivate AssistantOperationPrivate;

#define TYPE_STATUS_ICON (status_icon_get_type ())
#define STATUS_ICON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_STATUS_ICON, StatusIcon))
#define STATUS_ICON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_STATUS_ICON, StatusIconClass))
#define IS_STATUS_ICON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_STATUS_ICON))
#define IS_STATUS_ICON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_STATUS_ICON))
#define STATUS_ICON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_STATUS_ICON, StatusIconClass))

typedef struct _StatusIcon StatusIcon;
typedef struct _StatusIconClass StatusIconClass;

#define TYPE_ASSISTANT_RESTORE (assistant_restore_get_type ())
#define ASSISTANT_RESTORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ASSISTANT_RESTORE, AssistantRestore))
#define ASSISTANT_RESTORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ASSISTANT_RESTORE, AssistantRestoreClass))
#define IS_ASSISTANT_RESTORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ASSISTANT_RESTORE))
#define IS_ASSISTANT_RESTORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ASSISTANT_RESTORE))
#define ASSISTANT_RESTORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ASSISTANT_RESTORE, AssistantRestoreClass))

typedef struct _AssistantRestore AssistantRestore;
typedef struct _AssistantRestoreClass AssistantRestoreClass;
typedef struct _AssistantRestorePrivate AssistantRestorePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _deja_dup_operation_state_unref0(var) ((var == NULL) ? NULL : (var = (deja_dup_operation_state_unref (var), NULL)))

#define ASSISTANT_TYPE_TYPE (assistant_type_get_type ())
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))

#define TYPE_MOUNT_OPERATION_ASSISTANT (mount_operation_assistant_get_type ())
#define MOUNT_OPERATION_ASSISTANT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MOUNT_OPERATION_ASSISTANT, MountOperationAssistant))
#define MOUNT_OPERATION_ASSISTANT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MOUNT_OPERATION_ASSISTANT, MountOperationAssistantClass))
#define IS_MOUNT_OPERATION_ASSISTANT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MOUNT_OPERATION_ASSISTANT))
#define IS_MOUNT_OPERATION_ASSISTANT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MOUNT_OPERATION_ASSISTANT))
#define MOUNT_OPERATION_ASSISTANT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MOUNT_OPERATION_ASSISTANT, MountOperationAssistantClass))

typedef struct _MountOperationAssistant MountOperationAssistant;
typedef struct _MountOperationAssistantClass MountOperationAssistantClass;
typedef struct _AssistantRestoreDoQueryData AssistantRestoreDoQueryData;

struct _Assistant {
	GtkWindow parent_instance;
	AssistantPrivate * priv;
	GtkImage* header_icon;
	GtkEventBox* page_box;
	GList* current;
};

struct _AssistantClass {
	GtkWindowClass parent_class;
};

struct _AssistantOperation {
	Assistant parent_instance;
	AssistantOperationPrivate * priv;
	StatusIcon* status_icon;
	gboolean succeeded;
	gboolean nagged;
	GtkLabel* summary_label;
	GtkWidget* detail_widget;
	DejaDupOperation* op;
};

struct _AssistantOperationClass {
	AssistantClass parent_class;
	GtkWidget* (*make_confirm_page) (AssistantOperation* self);
	void (*add_setup_pages) (AssistantOperation* self);
	void (*add_custom_config_pages) (AssistantOperation* self);
	DejaDupOperation* (*create_op) (AssistantOperation* self);
	gchar* (*get_progress_file_prefix) (AssistantOperation* self);
	GtkWidget* (*make_progress_page) (AssistantOperation* self);
	void (*show_error) (AssistantOperation* self, const gchar* _error_, const gchar* detail);
	GtkWidget* (*make_summary_page) (AssistantOperation* self);
	void (*apply_finished) (AssistantOperation* self, DejaDupOperation* op, gboolean success, gboolean cancelled, const gchar* detail);
	void (*do_prepare) (AssistantOperation* self, Assistant* assist, GtkWidget* page);
	void (*do_cancel) (AssistantOperation* self);
	void (*do_close) (AssistantOperation* self);
};

struct _AssistantRestore {
	AssistantOperation parent_instance;
	AssistantRestorePrivate * priv;
	GList* _restore_files;
	DejaDupOperationStatus* query_op;
	DejaDupOperationState* op_state;
};

struct _AssistantRestoreClass {
	AssistantOperationClass parent_class;
	void (*handle_collection_dates) (AssistantRestore* self, DejaDupOperationStatus* op, GList* dates);
	void (*query_finished) (AssistantRestore* self, DejaDupOperation* op, gboolean success, gboolean cancelled, const gchar* detail);
};

struct _AssistantRestorePrivate {
	gchar* _restore_location;
	GtkProgressBar* query_progress_bar;
	guint query_timeout_id;
	GtkComboBoxText* date_combo;
	GtkListStore* date_store;
	GtkBox* cust_box;
	GtkFileChooserButton* cust_button;
	GtkGrid* confirm_table;
	GtkLabel* confirm_location_label;
	GtkLabel* confirm_location;
	GtkLabel* confirm_date_label;
	GtkLabel* confirm_date;
	GtkLabel* confirm_files_label;
	GtkGrid* confirm_files;
	GtkWidget* query_progress_page;
	GtkWidget* date_page;
	GtkWidget* restore_dest_page;
	gboolean got_dates;
};

typedef enum  {
	ASSISTANT_TYPE_NORMAL,
	ASSISTANT_TYPE_INTERRUPT,
	ASSISTANT_TYPE_CHECK,
	ASSISTANT_TYPE_SUMMARY,
	ASSISTANT_TYPE_PROGRESS,
	ASSISTANT_TYPE_FINISH
} AssistantType;

struct _AssistantRestoreDoQueryData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	AssistantRestore* self;
	DejaDupOperationStatus* _tmp0_;
	DejaDupOperationStatus* _tmp1_;
	DejaDupOperation* _tmp2_;
	DejaDupOperation* _tmp3_;
	DejaDupOperation* _tmp4_;
	DejaDupOperation* _tmp5_;
	DejaDupOperationStatus* _tmp6_;
	DejaDupOperation* _tmp7_;
	DejaDupBackend* _tmp8_;
	DejaDupBackend* _tmp9_;
	MountOperationAssistant* _tmp10_;
	MountOperationAssistant* _tmp11_;
	DejaDupOperation* _tmp12_;
	DejaDupBackend* _tmp13_;
	DejaDupBackend* _tmp14_;
	DejaDupOperation* _tmp15_;
};


static gpointer assistant_restore_parent_class = NULL;

GType assistant_get_type (void) G_GNUC_CONST;
gpointer assistant_page_info_ref (gpointer instance);
void assistant_page_info_unref (gpointer instance);
GParamSpec* assistant_param_spec_page_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void assistant_value_set_page_info (GValue* value, gpointer v_object);
void assistant_value_take_page_info (GValue* value, gpointer v_object);
gpointer assistant_value_get_page_info (const GValue* value);
GType assistant_page_info_get_type (void) G_GNUC_CONST;
GType assistant_operation_get_type (void) G_GNUC_CONST;
GType status_icon_get_type (void) G_GNUC_CONST;
GType assistant_restore_get_type (void) G_GNUC_CONST;
#define ASSISTANT_RESTORE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_ASSISTANT_RESTORE, AssistantRestorePrivate))
enum  {
	ASSISTANT_RESTORE_DUMMY_PROPERTY,
	ASSISTANT_RESTORE_RESTORE_LOCATION,
	ASSISTANT_RESTORE_RESTORE_FILES
};
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
AssistantRestore* assistant_restore_new_with_files (GList* files);
AssistantRestore* assistant_restore_construct_with_files (GType object_type, GList* files);
AssistantOperation* assistant_operation_construct (GType object_type);
void assistant_restore_set_restore_files (AssistantRestore* self, GList* value);
static void assistant_restore_real_add_setup_pages (AssistantOperation* base);
static void assistant_restore_add_query_backend_page (AssistantRestore* self);
static void assistant_restore_add_date_page (AssistantRestore* self);
static void assistant_restore_add_restore_dest_page (AssistantRestore* self);
static GtkWidget* assistant_restore_make_backup_location_page (AssistantRestore* self);
static void assistant_restore_real_add_custom_config_pages (AssistantOperation* base);
GList* assistant_restore_get_restore_files (AssistantRestore* self);
GType assistant_type_get_type (void) G_GNUC_CONST;
void assistant_append_page (Assistant* self, GtkWidget* page, AssistantType type);
void assistant_set_page_title (Assistant* self, GtkWidget* page, const gchar* title);
static GtkWidget* assistant_restore_make_query_backend_page (AssistantRestore* self);
static GtkWidget* assistant_restore_make_date_page (AssistantRestore* self);
static GtkWidget* assistant_restore_make_restore_dest_page (AssistantRestore* self);
static void __lambda31_ (AssistantRestore* self, GtkToggleButton* r);
void assistant_restore_set_restore_location (AssistantRestore* self, const gchar* value);
static void ___lambda31__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void __lambda32_ (AssistantRestore* self, GtkToggleButton* r);
static void ___lambda32__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void __lambda33_ (AssistantRestore* self, GtkFileChooser* b);
static void ___lambda33__gtk_file_chooser_selection_changed (GtkFileChooser* _sender, gpointer self);
static GtkWidget* assistant_restore_real_make_confirm_page (AssistantOperation* base);
static DejaDupOperation* assistant_restore_real_create_op (AssistantOperation* base);
const gchar* assistant_restore_get_restore_location (AssistantRestore* self);
static gchar* assistant_restore_real_get_progress_file_prefix (AssistantOperation* base);
static gboolean assistant_restore_is_same_day (AssistantRestore* self, GTimeVal* one, GTimeVal* two);
void assistant_restore_handle_collection_dates (AssistantRestore* self, DejaDupOperationStatus* op, GList* dates);
static void assistant_restore_real_handle_collection_dates (AssistantRestore* self, DejaDupOperationStatus* op, GList* dates);
static GTimeVal* _g_time_val_dup (GTimeVal* self);
void assistant_operation_show_error (AssistantOperation* self, const gchar* _error_, const gchar* detail);
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
void assistant_restore_query_finished (AssistantRestore* self, DejaDupOperation* op, gboolean success, gboolean cancelled, const gchar* detail);
static void assistant_restore_real_query_finished (AssistantRestore* self, DejaDupOperation* op, gboolean success, gboolean cancelled, const gchar* detail);
void assistant_operation_do_close (AssistantOperation* self);
void assistant_go_forward (Assistant* self);
static gboolean assistant_restore_query_pulse (AssistantRestore* self);
static void assistant_restore_do_query_data_free (gpointer _data);
void assistant_restore_do_query (AssistantRestore* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
void assistant_restore_do_query_finish (AssistantRestore* self, GAsyncResult* _res_);
static gboolean assistant_restore_do_query_co (AssistantRestoreDoQueryData* _data_);
static void _assistant_restore_query_finished_deja_dup_operation_done (DejaDupOperation* _sender, gboolean success, gboolean cancelled, const gchar* detail, gpointer self);
static void __lambda34_ (AssistantRestore* self, DejaDupOperation* o, const gchar* e, const gchar* d);
static void ___lambda34__deja_dup_operation_raise_error (DejaDupOperation* _sender, const gchar* errstr, const gchar* detail, gpointer self);
void assistant_operation_get_passphrase (AssistantOperation* self);
static void _assistant_operation_get_passphrase_deja_dup_operation_passphrase_required (DejaDupOperation* _sender, gpointer self);
static void _assistant_restore_handle_collection_dates_deja_dup_operation_status_collection_dates (DejaDupOperationStatus* _sender, GList* dates, gpointer self);
MountOperationAssistant* mount_operation_assistant_new (AssistantOperation* assist);
MountOperationAssistant* mount_operation_assistant_construct (GType object_type, AssistantOperation* assist);
GType mount_operation_assistant_get_type (void) G_GNUC_CONST;
void assistant_operation_pause_op (AssistantOperation* self, DejaDupBackend* back, const gchar* header, const gchar* msg);
static void _assistant_operation_pause_op_deja_dup_backend_pause_op (DejaDupBackend* _sender, const gchar* header, const gchar* msg, gpointer self);
static void assistant_restore_real_do_prepare (AssistantOperation* base, Assistant* assist, GtkWidget* page);
void assistant_operation_do_prepare (AssistantOperation* self, Assistant* assist, GtkWidget* page);
void assistant_skip (Assistant* self);
GtkWidget* assistant_operation_get_confirm_page (AssistantOperation* self);
static void ______lambda35_ (AssistantRestore* self, GtkWidget* w);
static void _______lambda35__gtk_callback (GtkWidget* widget, gpointer self);
GtkWidget* assistant_operation_get_summary_page (AssistantOperation* self);
gboolean assistant_operation_get_error_occurred (AssistantOperation* self);
GtkWidget* assistant_operation_get_progress_page (AssistantOperation* self);
gboolean assistant_get_last_op_was_back (Assistant* self);
static gboolean _assistant_restore_query_pulse_gsource_func (gpointer self);
void assistant_operation_provide_password (AssistantOperation* self);
static void assistant_restore_real_do_close (AssistantOperation* base);
AssistantRestore* assistant_restore_new (void);
AssistantRestore* assistant_restore_construct (GType object_type);
static GObject * assistant_restore_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
void assistant_set_apply_text (Assistant* self, const gchar* value);
static void assistant_restore_finalize (GObject* obj);
static void _vala_assistant_restore_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_assistant_restore_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


AssistantRestore* assistant_restore_construct_with_files (GType object_type, GList* files) {
	AssistantRestore * self = NULL;
	GList* _tmp0_;
	self = (AssistantRestore*) assistant_operation_construct (object_type);
	_tmp0_ = files;
	assistant_restore_set_restore_files (self, _tmp0_);
	return self;
}


AssistantRestore* assistant_restore_new_with_files (GList* files) {
	return assistant_restore_construct_with_files (TYPE_ASSISTANT_RESTORE, files);
}


static void assistant_restore_real_add_setup_pages (AssistantOperation* base) {
	AssistantRestore * self;
	self = (AssistantRestore*) base;
	assistant_restore_add_query_backend_page (self);
	assistant_restore_add_date_page (self);
	assistant_restore_add_restore_dest_page (self);
}


static GtkWidget* assistant_restore_make_backup_location_page (AssistantRestore* self) {
	GtkWidget* result = NULL;
	gint rows;
	GtkWidget* label = NULL;
	GtkSizeGroup* _tmp0_;
	GtkSizeGroup* label_sizes;
	GtkGrid* _tmp1_;
	GtkGrid* _tmp2_;
	GtkGrid* page;
	DejaDupConfigLocation* _tmp3_;
	DejaDupConfigLocation* _tmp4_;
	DejaDupConfigLocation* location;
	const gchar* _tmp5_ = NULL;
	GtkLabel* _tmp6_;
	GtkWidget* _tmp7_;
	gint _tmp8_;
	gint _tmp9_;
	gint _tmp10_;
	GtkEventBox* _tmp11_;
	GtkEventBox* _tmp12_;
	GtkEventBox* _tmp13_;
	GtkEventBox* _tmp14_;
	gint _tmp15_;
	gint _tmp16_;
	GtkRequisition req = {0};
	GtkRequisition hidden = {0};
	GtkRequisition _tmp17_ = {0};
	GtkRequisition _tmp18_ = {0};
	GtkRequisition _tmp19_;
	gint _tmp20_;
	GtkRequisition _tmp21_;
	gint _tmp22_;
	GtkRequisition _tmp23_;
	gint _tmp24_;
	GtkRequisition _tmp25_;
	gint _tmp26_;
	GtkRequisition _tmp27_;
	gint _tmp28_;
	GtkRequisition _tmp29_;
	gint _tmp30_;
	g_return_val_if_fail (self != NULL, NULL);
	rows = 0;
	_tmp0_ = gtk_size_group_new (GTK_SIZE_GROUP_HORIZONTAL);
	label_sizes = _tmp0_;
	_tmp1_ = (GtkGrid*) gtk_grid_new ();
	_tmp2_ = g_object_ref_sink (_tmp1_);
	page = _tmp2_;
	g_object_set ((GObject*) page, "row-spacing", 6, "column-spacing", 12, "border-width", 12, NULL);
	_tmp3_ = deja_dup_config_location_new (label_sizes);
	_tmp4_ = g_object_ref_sink (_tmp3_);
	location = _tmp4_;
	_tmp5_ = _ ("_Backup location");
	_tmp6_ = (GtkLabel*) gtk_label_new_with_mnemonic (_tmp5_);
	_tmp7_ = (GtkWidget*) g_object_ref_sink (_tmp6_);
	_g_object_unref0 (label);
	label = _tmp7_;
	g_object_set ((GObject*) label, "xalign", 1.0f, "mnemonic-widget", location, NULL);
	gtk_size_group_add_widget (label_sizes, label);
	_tmp8_ = rows;
	gtk_grid_attach (page, label, 0, _tmp8_, 1, 1);
	g_object_set ((GObject*) location, "hexpand", TRUE, NULL);
	_tmp9_ = rows;
	gtk_grid_attach (page, (GtkWidget*) location, 1, _tmp9_, 1, 1);
	_tmp10_ = rows;
	rows = _tmp10_ + 1;
	_tmp11_ = deja_dup_config_location_get_extras (location);
	_tmp12_ = _tmp11_;
	g_object_set ((GObject*) _tmp12_, "hexpand", TRUE, NULL);
	_tmp13_ = deja_dup_config_location_get_extras (location);
	_tmp14_ = _tmp13_;
	_tmp15_ = rows;
	gtk_grid_attach (page, (GtkWidget*) _tmp14_, 0, _tmp15_, 2, 1);
	_tmp16_ = rows;
	rows = _tmp16_ + 1;
	gtk_widget_show_all ((GtkWidget*) page);
	gtk_widget_get_preferred_size ((GtkWidget*) page, NULL, &_tmp17_);
	req = _tmp17_;
	deja_dup_config_location_hidden_size (location, &_tmp18_);
	hidden = _tmp18_;
	_tmp19_ = req;
	_tmp20_ = _tmp19_.width;
	_tmp21_ = hidden;
	_tmp22_ = _tmp21_.width;
	req.width = _tmp20_ + _tmp22_;
	_tmp23_ = req;
	_tmp24_ = _tmp23_.height;
	_tmp25_ = hidden;
	_tmp26_ = _tmp25_.height;
	req.height = _tmp24_ + _tmp26_;
	_tmp27_ = req;
	_tmp28_ = _tmp27_.width;
	_tmp29_ = req;
	_tmp30_ = _tmp29_.height;
	gtk_widget_set_size_request ((GtkWidget*) page, _tmp28_, _tmp30_);
	result = (GtkWidget*) page;
	_g_object_unref0 (location);
	_g_object_unref0 (label_sizes);
	_g_object_unref0 (label);
	return result;
}


static void assistant_restore_real_add_custom_config_pages (AssistantOperation* base) {
	AssistantRestore * self;
	gboolean _tmp0_ = FALSE;
	GList* _tmp1_;
	GList* _tmp2_;
	gboolean _tmp4_;
	self = (AssistantRestore*) base;
	_tmp1_ = assistant_restore_get_restore_files (self);
	_tmp2_ = _tmp1_;
	if (_tmp2_ == NULL) {
		_tmp0_ = TRUE;
	} else {
		gboolean _tmp3_ = FALSE;
		_tmp3_ = deja_dup_has_seen_settings ();
		_tmp0_ = !_tmp3_;
	}
	_tmp4_ = _tmp0_;
	if (_tmp4_) {
		GtkWidget* _tmp5_ = NULL;
		GtkWidget* page;
		GtkWidget* _tmp6_;
		GtkWidget* _tmp7_;
		const gchar* _tmp8_ = NULL;
		_tmp5_ = assistant_restore_make_backup_location_page (self);
		page = _tmp5_;
		_tmp6_ = page;
		assistant_append_page ((Assistant*) self, _tmp6_, ASSISTANT_TYPE_NORMAL);
		_tmp7_ = page;
		_tmp8_ = _ ("Restore From Where?");
		assistant_set_page_title ((Assistant*) self, _tmp7_, _tmp8_);
		_g_object_unref0 (page);
	}
}


static GtkWidget* assistant_restore_make_query_backend_page (AssistantRestore* self) {
	GtkWidget* result = NULL;
	GtkProgressBar* _tmp0_;
	GtkProgressBar* _tmp1_;
	GtkBox* _tmp2_;
	GtkBox* _tmp3_;
	GtkBox* page;
	GtkProgressBar* _tmp4_;
	GtkProgressBar* _tmp5_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = (GtkProgressBar*) gtk_progress_bar_new ();
	_tmp1_ = g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->query_progress_bar);
	self->priv->query_progress_bar = _tmp1_;
	_tmp2_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 6);
	_tmp3_ = g_object_ref_sink (_tmp2_);
	page = _tmp3_;
	_tmp4_ = self->priv->query_progress_bar;
	g_object_set ((GObject*) page, "child", _tmp4_, "border-width", 12, NULL);
	_tmp5_ = self->priv->query_progress_bar;
	gtk_container_child_set ((GtkContainer*) page, (GtkWidget*) _tmp5_, "expand", FALSE, NULL);
	result = (GtkWidget*) page;
	return result;
}


static GtkWidget* assistant_restore_make_date_page (AssistantRestore* self) {
	GtkWidget* result = NULL;
	GtkListStore* _tmp0_;
	GtkComboBoxText* _tmp1_;
	GtkComboBoxText* _tmp2_;
	GtkComboBoxText* _tmp3_;
	GtkListStore* _tmp4_;
	const gchar* _tmp5_ = NULL;
	GtkLabel* _tmp6_;
	GtkLabel* _tmp7_;
	GtkLabel* date_label;
	GtkComboBoxText* _tmp8_;
	GtkBox* _tmp9_;
	GtkBox* _tmp10_;
	GtkBox* hbox;
	GtkComboBoxText* _tmp11_;
	GtkBox* _tmp12_;
	GtkBox* _tmp13_;
	GtkBox* page;
	GtkComboBoxText* _tmp14_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gtk_list_store_new (2, G_TYPE_STRING, G_TYPE_STRING);
	_g_object_unref0 (self->priv->date_store);
	self->priv->date_store = _tmp0_;
	_tmp1_ = (GtkComboBoxText*) gtk_combo_box_text_new ();
	_tmp2_ = g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->date_combo);
	self->priv->date_combo = _tmp2_;
	_tmp3_ = self->priv->date_combo;
	_tmp4_ = self->priv->date_store;
	gtk_combo_box_set_model ((GtkComboBox*) _tmp3_, (GtkTreeModel*) _tmp4_);
	_tmp5_ = _ ("_Date");
	_tmp6_ = (GtkLabel*) gtk_label_new (_tmp5_);
	_tmp7_ = g_object_ref_sink (_tmp6_);
	date_label = _tmp7_;
	_tmp8_ = self->priv->date_combo;
	g_object_set ((GObject*) date_label, "mnemonic-widget", _tmp8_, "use-underline", TRUE, "xalign", 1.0f, NULL);
	_tmp9_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 6);
	_tmp10_ = g_object_ref_sink (_tmp9_);
	hbox = _tmp10_;
	_tmp11_ = self->priv->date_combo;
	g_object_set ((GObject*) hbox, "child", date_label, "child", _tmp11_, NULL);
	_tmp12_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 6);
	_tmp13_ = g_object_ref_sink (_tmp12_);
	page = _tmp13_;
	g_object_set ((GObject*) page, "child", hbox, "border-width", 12, NULL);
	gtk_container_child_set ((GtkContainer*) hbox, (GtkWidget*) date_label, "expand", FALSE, NULL);
	_tmp14_ = self->priv->date_combo;
	gtk_container_child_set ((GtkContainer*) hbox, (GtkWidget*) _tmp14_, "expand", FALSE, NULL);
	gtk_container_child_set ((GtkContainer*) page, (GtkWidget*) hbox, "expand", FALSE, NULL);
	result = (GtkWidget*) page;
	_g_object_unref0 (hbox);
	_g_object_unref0 (date_label);
	return result;
}


static void __lambda31_ (AssistantRestore* self, GtkToggleButton* r) {
	GtkToggleButton* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
	g_return_if_fail (r != NULL);
	_tmp0_ = r;
	_tmp1_ = gtk_toggle_button_get_active (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		assistant_restore_set_restore_location (self, "/");
	}
}


static void ___lambda31__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	__lambda31_ (self, _sender);
}


static void __lambda32_ (AssistantRestore* self, GtkToggleButton* r) {
	GtkToggleButton* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
	GtkBox* _tmp6_;
	GtkToggleButton* _tmp7_;
	gboolean _tmp8_;
	gboolean _tmp9_;
	g_return_if_fail (r != NULL);
	_tmp0_ = r;
	_tmp1_ = gtk_toggle_button_get_active (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		GtkFileChooserButton* _tmp3_;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_;
		_tmp3_ = self->priv->cust_button;
		_tmp4_ = gtk_file_chooser_get_filename ((GtkFileChooser*) _tmp3_);
		_tmp5_ = _tmp4_;
		assistant_restore_set_restore_location (self, _tmp5_);
		_g_free0 (_tmp5_);
	}
	_tmp6_ = self->priv->cust_box;
	_tmp7_ = r;
	_tmp8_ = gtk_toggle_button_get_active (_tmp7_);
	_tmp9_ = _tmp8_;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp6_, _tmp9_);
}


static void ___lambda32__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	__lambda32_ (self, _sender);
}


static void __lambda33_ (AssistantRestore* self, GtkFileChooser* b) {
	GtkFileChooser* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	g_return_if_fail (b != NULL);
	_tmp0_ = b;
	_tmp1_ = gtk_file_chooser_get_filename (_tmp0_);
	_tmp2_ = _tmp1_;
	assistant_restore_set_restore_location (self, _tmp2_);
	_g_free0 (_tmp2_);
}


static void ___lambda33__gtk_file_chooser_selection_changed (GtkFileChooser* _sender, gpointer self) {
	__lambda33_ (self, _sender);
}


static GtkWidget* assistant_restore_make_restore_dest_page (AssistantRestore* self) {
	GtkWidget* result = NULL;
	GtkRadioButton* _tmp0_;
	GtkRadioButton* _tmp1_;
	GtkRadioButton* orig_radio;
	const gchar* _tmp2_ = NULL;
	GtkRadioButton* _tmp3_;
	GtkRadioButton* _tmp4_;
	GtkRadioButton* cust_radio;
	const gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	GtkFileChooserButton* _tmp7_;
	GtkFileChooserButton* _tmp8_;
	GtkFileChooserButton* _tmp9_;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_;
	gchar* _tmp12_;
	GtkLabel* _tmp13_;
	GtkLabel* _tmp14_;
	GtkLabel* _tmp15_;
	GtkLabel* cust_label;
	GtkFileChooserButton* _tmp16_;
	GtkBox* _tmp17_;
	GtkBox* _tmp18_;
	GtkBox* _tmp19_;
	GtkFileChooserButton* _tmp20_;
	GtkBox* _tmp21_;
	GtkBox* _tmp22_;
	GtkBox* page;
	GtkBox* _tmp23_;
	GtkBox* _tmp24_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = (GtkRadioButton*) gtk_radio_button_new (NULL);
	_tmp1_ = g_object_ref_sink (_tmp0_);
	orig_radio = _tmp1_;
	_tmp2_ = _ ("Restore files to _original locations");
	g_object_set ((GObject*) orig_radio, "label", _tmp2_, "use-underline", TRUE, NULL);
	g_signal_connect_object ((GtkToggleButton*) orig_radio, "toggled", (GCallback) ___lambda31__gtk_toggle_button_toggled, self, 0);
	_tmp3_ = (GtkRadioButton*) gtk_radio_button_new (NULL);
	_tmp4_ = g_object_ref_sink (_tmp3_);
	cust_radio = _tmp4_;
	_tmp5_ = _ ("Restore to _specific folder");
	g_object_set ((GObject*) cust_radio, "label", _tmp5_, "use-underline", TRUE, "group", orig_radio, NULL);
	g_signal_connect_object ((GtkToggleButton*) cust_radio, "toggled", (GCallback) ___lambda32__gtk_toggle_button_toggled, self, 0);
	_tmp6_ = _ ("Choose destination for restored files");
	_tmp7_ = (GtkFileChooserButton*) gtk_file_chooser_button_new (_tmp6_, GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
	_tmp8_ = g_object_ref_sink (_tmp7_);
	_g_object_unref0 (self->priv->cust_button);
	self->priv->cust_button = _tmp8_;
	_tmp9_ = self->priv->cust_button;
	g_signal_connect_object ((GtkFileChooser*) _tmp9_, "selection-changed", (GCallback) ___lambda33__gtk_file_chooser_selection_changed, self, 0);
	_tmp10_ = _ ("Restore _folder");
	_tmp11_ = g_strconcat ("    ", _tmp10_, NULL);
	_tmp12_ = _tmp11_;
	_tmp13_ = (GtkLabel*) gtk_label_new (_tmp12_);
	_tmp14_ = g_object_ref_sink (_tmp13_);
	_tmp15_ = _tmp14_;
	_g_free0 (_tmp12_);
	cust_label = _tmp15_;
	_tmp16_ = self->priv->cust_button;
	g_object_set ((GObject*) cust_label, "mnemonic-widget", _tmp16_, "use-underline", TRUE, "xalign", 1.0f, NULL);
	_tmp17_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 6);
	_tmp18_ = g_object_ref_sink (_tmp17_);
	_g_object_unref0 (self->priv->cust_box);
	self->priv->cust_box = _tmp18_;
	_tmp19_ = self->priv->cust_box;
	_tmp20_ = self->priv->cust_button;
	g_object_set ((GObject*) _tmp19_, "child", cust_label, "child", _tmp20_, "sensitive", FALSE, NULL);
	_tmp21_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 6);
	_tmp22_ = g_object_ref_sink (_tmp21_);
	page = _tmp22_;
	_tmp23_ = self->priv->cust_box;
	g_object_set ((GObject*) page, "child", orig_radio, "child", cust_radio, "child", _tmp23_, "border-width", 12, NULL);
	gtk_container_child_set ((GtkContainer*) page, (GtkWidget*) orig_radio, "expand", FALSE, NULL);
	gtk_container_child_set ((GtkContainer*) page, (GtkWidget*) cust_radio, "expand", FALSE, NULL);
	_tmp24_ = self->priv->cust_box;
	gtk_container_child_set ((GtkContainer*) page, (GtkWidget*) _tmp24_, "expand", FALSE, NULL);
	result = (GtkWidget*) page;
	_g_object_unref0 (cust_label);
	_g_object_unref0 (cust_radio);
	_g_object_unref0 (orig_radio);
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static GtkWidget* assistant_restore_real_make_confirm_page (AssistantOperation* base) {
	AssistantRestore * self;
	GtkWidget* result = NULL;
	gint rows;
	GtkWidget* label = NULL;
	GtkWidget* w = NULL;
	GtkGrid* _tmp0_;
	GtkGrid* _tmp1_;
	GtkGrid* _tmp2_;
	GtkGrid* _tmp3_;
	GtkGrid* page;
	const gchar* _tmp4_ = NULL;
	GtkLabel* _tmp5_;
	GtkWidget* _tmp6_;
	DejaDupConfigLabelLocation* _tmp7_;
	GtkWidget* _tmp8_;
	gint _tmp9_;
	gint _tmp10_;
	gint _tmp11_;
	const gchar* _tmp12_ = NULL;
	GtkLabel* _tmp13_;
	GtkLabel* _tmp14_;
	GtkLabel* _tmp15_;
	GtkLabel* _tmp16_;
	GtkLabel* _tmp17_;
	GtkLabel* _tmp18_;
	GtkLabel* _tmp19_;
	gint _tmp20_;
	GtkLabel* _tmp21_;
	gint _tmp22_;
	gint _tmp23_;
	const gchar* _tmp24_ = NULL;
	GtkLabel* _tmp25_;
	GtkLabel* _tmp26_;
	GtkLabel* _tmp27_;
	GtkLabel* _tmp28_;
	GtkLabel* _tmp29_;
	GtkLabel* _tmp30_;
	GtkLabel* _tmp31_;
	gint _tmp32_;
	GtkLabel* _tmp33_;
	gint _tmp34_;
	gint _tmp35_;
	GtkLabel* _tmp36_;
	GtkLabel* _tmp37_;
	GtkLabel* _tmp38_;
	GtkGrid* _tmp39_;
	GtkGrid* _tmp40_;
	GtkGrid* _tmp41_;
	GtkGrid* _tmp42_;
	GtkGrid* _tmp43_;
	GtkGrid* _tmp44_;
	GtkLabel* _tmp45_;
	gint _tmp46_;
	GtkGrid* _tmp47_;
	gint _tmp48_;
	gint _tmp49_;
	self = (AssistantRestore*) base;
	rows = 0;
	_tmp0_ = (GtkGrid*) gtk_grid_new ();
	_tmp1_ = g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->confirm_table);
	self->priv->confirm_table = _tmp1_;
	_tmp2_ = self->priv->confirm_table;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	page = _tmp3_;
	g_object_set ((GObject*) page, "row-spacing", 6, "column-spacing", 12, "border-width", 12, NULL);
	_tmp4_ = _ ("Backup location");
	_tmp5_ = (GtkLabel*) gtk_label_new (_tmp4_);
	_tmp6_ = (GtkWidget*) g_object_ref_sink (_tmp5_);
	_g_object_unref0 (label);
	label = _tmp6_;
	g_object_set ((GObject*) label, "xalign", 1.0f, "yalign", 0.0f, NULL);
	_tmp7_ = deja_dup_config_label_location_new ();
	_tmp8_ = (GtkWidget*) g_object_ref_sink (_tmp7_);
	_g_object_unref0 (w);
	w = _tmp8_;
	g_object_set ((GObject*) w, "hexpand", TRUE, NULL);
	_tmp9_ = rows;
	gtk_grid_attach (page, label, 0, _tmp9_, 1, 1);
	_tmp10_ = rows;
	gtk_grid_attach (page, w, 1, _tmp10_, 1, 1);
	_tmp11_ = rows;
	rows = _tmp11_ + 1;
	_tmp12_ = _ ("Restore date");
	_tmp13_ = (GtkLabel*) gtk_label_new (_tmp12_);
	_tmp14_ = g_object_ref_sink (_tmp13_);
	_g_object_unref0 (self->priv->confirm_date_label);
	self->priv->confirm_date_label = _tmp14_;
	_tmp15_ = self->priv->confirm_date_label;
	g_object_set ((GObject*) _tmp15_, "xalign", 1.0f, NULL);
	_tmp16_ = (GtkLabel*) gtk_label_new ("");
	_tmp17_ = g_object_ref_sink (_tmp16_);
	_g_object_unref0 (self->priv->confirm_date);
	self->priv->confirm_date = _tmp17_;
	_tmp18_ = self->priv->confirm_date;
	g_object_set ((GObject*) _tmp18_, "xalign", 0.0f, NULL);
	_tmp19_ = self->priv->confirm_date_label;
	_tmp20_ = rows;
	gtk_grid_attach (page, (GtkWidget*) _tmp19_, 0, _tmp20_, 1, 1);
	_tmp21_ = self->priv->confirm_date;
	_tmp22_ = rows;
	gtk_grid_attach (page, (GtkWidget*) _tmp21_, 1, _tmp22_, 1, 1);
	_tmp23_ = rows;
	rows = _tmp23_ + 1;
	_tmp24_ = _ ("Restore folder");
	_tmp25_ = (GtkLabel*) gtk_label_new (_tmp24_);
	_tmp26_ = g_object_ref_sink (_tmp25_);
	_g_object_unref0 (self->priv->confirm_location_label);
	self->priv->confirm_location_label = _tmp26_;
	_tmp27_ = self->priv->confirm_location_label;
	g_object_set ((GObject*) _tmp27_, "xalign", 1.0f, NULL);
	_tmp28_ = (GtkLabel*) gtk_label_new ("");
	_tmp29_ = g_object_ref_sink (_tmp28_);
	_g_object_unref0 (self->priv->confirm_location);
	self->priv->confirm_location = _tmp29_;
	_tmp30_ = self->priv->confirm_location;
	g_object_set ((GObject*) _tmp30_, "xalign", 0.0f, NULL);
	_tmp31_ = self->priv->confirm_location_label;
	_tmp32_ = rows;
	gtk_grid_attach (page, (GtkWidget*) _tmp31_, 0, _tmp32_, 1, 1);
	_tmp33_ = self->priv->confirm_location;
	_tmp34_ = rows;
	gtk_grid_attach (page, (GtkWidget*) _tmp33_, 1, _tmp34_, 1, 1);
	_tmp35_ = rows;
	rows = _tmp35_ + 1;
	_tmp36_ = (GtkLabel*) gtk_label_new ("");
	_tmp37_ = g_object_ref_sink (_tmp36_);
	_g_object_unref0 (self->priv->confirm_files_label);
	self->priv->confirm_files_label = _tmp37_;
	_tmp38_ = self->priv->confirm_files_label;
	g_object_set ((GObject*) _tmp38_, "xalign", 1.0f, "yalign", 0.0f, NULL);
	_tmp39_ = (GtkGrid*) gtk_grid_new ();
	_tmp40_ = g_object_ref_sink (_tmp39_);
	_g_object_unref0 (self->priv->confirm_files);
	self->priv->confirm_files = _tmp40_;
	_tmp41_ = self->priv->confirm_files;
	gtk_orientable_set_orientation ((GtkOrientable*) _tmp41_, GTK_ORIENTATION_VERTICAL);
	_tmp42_ = self->priv->confirm_files;
	gtk_grid_set_row_spacing (_tmp42_, 6);
	_tmp43_ = self->priv->confirm_files;
	gtk_grid_set_column_spacing (_tmp43_, 6);
	_tmp44_ = self->priv->confirm_files;
	gtk_grid_set_row_homogeneous (_tmp44_, TRUE);
	_tmp45_ = self->priv->confirm_files_label;
	_tmp46_ = rows;
	gtk_grid_attach (page, (GtkWidget*) _tmp45_, 0, _tmp46_, 1, 1);
	_tmp47_ = self->priv->confirm_files;
	_tmp48_ = rows;
	gtk_grid_attach (page, (GtkWidget*) _tmp47_, 1, _tmp48_, 1, 1);
	_tmp49_ = rows;
	rows = _tmp49_ + 1;
	result = (GtkWidget*) page;
	_g_object_unref0 (w);
	_g_object_unref0 (label);
	return result;
}


static void assistant_restore_add_query_backend_page (AssistantRestore* self) {
	GtkWidget* _tmp0_ = NULL;
	GtkWidget* page;
	const gchar* _tmp1_ = NULL;
	GtkWidget* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = assistant_restore_make_query_backend_page (self);
	page = _tmp0_;
	assistant_append_page ((Assistant*) self, page, ASSISTANT_TYPE_PROGRESS);
	_tmp1_ = _ ("Checking for Backups…");
	assistant_set_page_title ((Assistant*) self, page, _tmp1_);
	_tmp2_ = _g_object_ref0 (page);
	_g_object_unref0 (self->priv->query_progress_page);
	self->priv->query_progress_page = _tmp2_;
	_g_object_unref0 (page);
}


static void assistant_restore_add_date_page (AssistantRestore* self) {
	GtkWidget* _tmp0_ = NULL;
	GtkWidget* page;
	const gchar* _tmp1_ = NULL;
	GtkWidget* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = assistant_restore_make_date_page (self);
	page = _tmp0_;
	assistant_append_page ((Assistant*) self, page, ASSISTANT_TYPE_NORMAL);
	_tmp1_ = _ ("Restore From When?");
	assistant_set_page_title ((Assistant*) self, page, _tmp1_);
	_tmp2_ = _g_object_ref0 (page);
	_g_object_unref0 (self->priv->date_page);
	self->priv->date_page = _tmp2_;
	_g_object_unref0 (page);
}


static void assistant_restore_add_restore_dest_page (AssistantRestore* self) {
	GtkWidget* _tmp0_ = NULL;
	GtkWidget* page;
	const gchar* _tmp1_ = NULL;
	GtkWidget* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = assistant_restore_make_restore_dest_page (self);
	page = _tmp0_;
	assistant_append_page ((Assistant*) self, page, ASSISTANT_TYPE_NORMAL);
	_tmp1_ = _ ("Restore to Where?");
	assistant_set_page_title ((Assistant*) self, page, _tmp1_);
	_tmp2_ = _g_object_ref0 (page);
	_g_object_unref0 (self->priv->restore_dest_page);
	self->priv->restore_dest_page = _tmp2_;
	_g_object_unref0 (page);
}


static DejaDupOperation* assistant_restore_real_create_op (AssistantOperation* base) {
	AssistantRestore * self;
	DejaDupOperation* result = NULL;
	gchar* date;
	gboolean _tmp0_;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	GList* _tmp8_;
	GList* _tmp9_;
	DejaDupOperationRestore* _tmp10_;
	DejaDupOperationRestore* rest_op;
	DejaDupOperationState* _tmp11_;
	self = (AssistantRestore*) base;
	date = NULL;
	_tmp0_ = self->priv->got_dates;
	if (_tmp0_) {
		GtkTreeIter iter = {0};
		GtkComboBoxText* _tmp1_;
		GtkTreeIter _tmp2_ = {0};
		gboolean _tmp3_ = FALSE;
		_tmp1_ = self->priv->date_combo;
		_tmp3_ = gtk_combo_box_get_active_iter ((GtkComboBox*) _tmp1_, &_tmp2_);
		iter = _tmp2_;
		if (_tmp3_) {
			GtkListStore* _tmp4_;
			GtkTreeIter _tmp5_;
			_tmp4_ = self->priv->date_store;
			_tmp5_ = iter;
			gtk_tree_model_get ((GtkTreeModel*) _tmp4_, &_tmp5_, 1, &date, -1);
		}
	}
	gtk_widget_realize ((GtkWidget*) self);
	_tmp6_ = self->priv->_restore_location;
	_tmp7_ = date;
	_tmp8_ = assistant_restore_get_restore_files (self);
	_tmp9_ = _tmp8_;
	_tmp10_ = deja_dup_operation_restore_new (_tmp6_, _tmp7_, _tmp9_);
	rest_op = _tmp10_;
	_tmp11_ = self->op_state;
	if (_tmp11_ != NULL) {
		DejaDupOperationRestore* _tmp12_;
		DejaDupOperationState* _tmp13_;
		_tmp12_ = rest_op;
		_tmp13_ = self->op_state;
		deja_dup_operation_set_state ((DejaDupOperation*) _tmp12_, _tmp13_);
	}
	result = (DejaDupOperation*) rest_op;
	_g_free0 (date);
	return result;
}


static gchar* assistant_restore_real_get_progress_file_prefix (AssistantOperation* base) {
	AssistantRestore * self;
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	self = (AssistantRestore*) base;
	_tmp0_ = _ ("Restoring:");
	_tmp1_ = g_strdup (_tmp0_);
	result = _tmp1_;
	return result;
}


static gboolean assistant_restore_is_same_day (AssistantRestore* self, GTimeVal* one, GTimeVal* two) {
	gboolean result = FALSE;
	GDate day1 = {0};
	GDate day2 = {0};
	GTimeVal _tmp0_;
	GTimeVal _tmp1_;
	GDate _tmp2_;
	gint _tmp3_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (one != NULL, FALSE);
	g_return_val_if_fail (two != NULL, FALSE);
	memset (&day1, 0, sizeof (GDate));
	memset (&day2, 0, sizeof (GDate));
	_tmp0_ = *one;
	g_date_set_time_val (&day1, &_tmp0_);
	_tmp1_ = *two;
	g_date_set_time_val (&day2, &_tmp1_);
	_tmp2_ = day2;
	_tmp3_ = g_date_compare (&day1, &_tmp2_);
	result = _tmp3_ == 0;
	return result;
}


static GTimeVal* _g_time_val_dup (GTimeVal* self) {
	GTimeVal* dup;
	dup = g_new0 (GTimeVal, 1);
	memcpy (dup, self, sizeof (GTimeVal));
	return dup;
}


static gpointer __g_time_val_dup0 (gpointer self) {
	return self ? _g_time_val_dup (self) : NULL;
}


static void g_time_local (time_t time, struct tm* result) {
	struct tm _result_ = {0};
	struct tm _tmp0_ = {0};
	localtime_r (&time, &_tmp0_);
	_result_ = _tmp0_;
	*result = _result_;
	return;
}


static gchar* g_time_format (struct tm *self, const gchar* format) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* buffer;
	gint buffer_length1;
	gint _buffer_size_;
	gchar* _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gint _tmp3__length1;
	gchar* _tmp4_;
	g_return_val_if_fail (format != NULL, NULL);
	_tmp0_ = g_new0 (gchar, 64);
	buffer = _tmp0_;
	buffer_length1 = 64;
	_buffer_size_ = buffer_length1;
	_tmp1_ = buffer;
	_tmp1__length1 = buffer_length1;
	_tmp2_ = format;
	strftime (_tmp1_, _tmp1__length1, _tmp2_, &(*self));
	_tmp3_ = buffer;
	_tmp3__length1 = buffer_length1;
	_tmp4_ = g_strdup ((const gchar*) _tmp3_);
	result = _tmp4_;
	buffer = (g_free (buffer), NULL);
	return result;
}


static void _g_free0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_free (var), NULL));
}


static void _g_list_free__g_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
	g_list_free (self);
}


static void assistant_restore_real_handle_collection_dates (AssistantRestore* self, DejaDupOperationStatus* op, GList* dates) {
	GList* timevals;
	GTimeVal tv = {0};
	GtkListStore* _tmp0_;
	GList* _tmp1_;
	GtkListStore* _tmp54_;
	gint _tmp55_ = 0;
	g_return_if_fail (op != NULL);
	timevals = NULL;
	g_get_current_time (&tv);
	self->priv->got_dates = TRUE;
	_tmp0_ = self->priv->date_store;
	gtk_list_store_clear (_tmp0_);
	_tmp1_ = dates;
	{
		GList* date_collection = NULL;
		GList* date_it = NULL;
		date_collection = _tmp1_;
		for (date_it = date_collection; date_it != NULL; date_it = date_it->next) {
			gchar* _tmp2_;
			gchar* date = NULL;
			_tmp2_ = g_strdup ((const gchar*) date_it->data);
			date = _tmp2_;
			{
				const gchar* _tmp3_;
				gboolean _tmp4_ = FALSE;
				_tmp3_ = date;
				_tmp4_ = g_time_val_from_iso8601 (_tmp3_, &tv);
				if (_tmp4_) {
					GTimeVal _tmp5_;
					GTimeVal* _tmp6_;
					_tmp5_ = tv;
					_tmp6_ = __g_time_val_dup0 (&_tmp5_);
					timevals = g_list_append (timevals, _tmp6_);
				}
				_g_free0 (date);
			}
		}
	}
	{
		GList* _tmp7_;
		GList* i;
		_tmp7_ = timevals;
		i = _tmp7_;
		{
			gboolean _tmp8_;
			_tmp8_ = TRUE;
			while (TRUE) {
				gboolean _tmp9_;
				GList* _tmp12_;
				GList* _tmp13_;
				gconstpointer _tmp14_;
				gchar* _tmp15_;
				gchar* format;
				gboolean _tmp16_ = FALSE;
				gboolean _tmp17_ = FALSE;
				GList* _tmp18_;
				GList* _tmp19_;
				gboolean _tmp26_;
				gboolean _tmp37_;
				GTimeVal _tmp40_;
				glong _tmp41_;
				struct tm _tmp42_ = {0};
				struct tm t;
				const gchar* _tmp43_;
				gchar* _tmp44_ = NULL;
				gchar* user_str;
				GtkTreeIter iter = {0};
				GtkListStore* _tmp45_;
				GtkTreeIter _tmp46_ = {0};
				GtkListStore* _tmp47_;
				GtkTreeIter _tmp48_;
				const gchar* _tmp49_;
				gchar* _tmp50_ = NULL;
				gchar* _tmp51_;
				GtkComboBoxText* _tmp52_;
				GtkTreeIter _tmp53_;
				_tmp9_ = _tmp8_;
				if (!_tmp9_) {
					GList* _tmp10_;
					GList* _tmp11_;
					_tmp10_ = i;
					_tmp11_ = _tmp10_->next;
					i = _tmp11_;
				}
				_tmp8_ = FALSE;
				_tmp12_ = i;
				if (!(_tmp12_ != NULL)) {
					break;
				}
				_tmp13_ = i;
				_tmp14_ = _tmp13_->data;
				tv = *((GTimeVal*) _tmp14_);
				_tmp15_ = g_strdup ("%x");
				format = _tmp15_;
				_tmp18_ = i;
				_tmp19_ = _tmp18_->prev;
				if (_tmp19_ != NULL) {
					GList* _tmp20_;
					GList* _tmp21_;
					gconstpointer _tmp22_;
					GTimeVal _tmp23_;
					GTimeVal _tmp24_;
					gboolean _tmp25_ = FALSE;
					_tmp20_ = i;
					_tmp21_ = _tmp20_->prev;
					_tmp22_ = _tmp21_->data;
					_tmp23_ = tv;
					_tmp24_ = *((GTimeVal*) _tmp22_);
					_tmp25_ = assistant_restore_is_same_day (self, &_tmp24_, &_tmp23_);
					_tmp17_ = _tmp25_;
				} else {
					_tmp17_ = FALSE;
				}
				_tmp26_ = _tmp17_;
				if (_tmp26_) {
					_tmp16_ = TRUE;
				} else {
					gboolean _tmp27_ = FALSE;
					GList* _tmp28_;
					GList* _tmp29_;
					gboolean _tmp36_;
					_tmp28_ = i;
					_tmp29_ = _tmp28_->next;
					if (_tmp29_ != NULL) {
						GList* _tmp30_;
						GList* _tmp31_;
						gconstpointer _tmp32_;
						GTimeVal _tmp33_;
						GTimeVal _tmp34_;
						gboolean _tmp35_ = FALSE;
						_tmp30_ = i;
						_tmp31_ = _tmp30_->next;
						_tmp32_ = _tmp31_->data;
						_tmp33_ = tv;
						_tmp34_ = *((GTimeVal*) _tmp32_);
						_tmp35_ = assistant_restore_is_same_day (self, &_tmp34_, &_tmp33_);
						_tmp27_ = _tmp35_;
					} else {
						_tmp27_ = FALSE;
					}
					_tmp36_ = _tmp27_;
					_tmp16_ = _tmp36_;
				}
				_tmp37_ = _tmp16_;
				if (_tmp37_) {
					const gchar* _tmp38_ = NULL;
					gchar* _tmp39_;
					_tmp38_ = _ ("%x %X");
					_tmp39_ = g_strdup (_tmp38_);
					_g_free0 (format);
					format = _tmp39_;
				}
				_tmp40_ = tv;
				_tmp41_ = _tmp40_.tv_sec;
				g_time_local ((time_t) _tmp41_, &_tmp42_);
				t = _tmp42_;
				_tmp43_ = format;
				_tmp44_ = g_time_format (&t, _tmp43_);
				user_str = _tmp44_;
				_tmp45_ = self->priv->date_store;
				gtk_list_store_prepend (_tmp45_, &_tmp46_);
				iter = _tmp46_;
				_tmp47_ = self->priv->date_store;
				_tmp48_ = iter;
				_tmp49_ = user_str;
				_tmp50_ = g_time_val_to_iso8601 (&tv);
				_tmp51_ = _tmp50_;
				gtk_list_store_set (_tmp47_, &_tmp48_, 0, _tmp49_, 1, _tmp51_, -1);
				_g_free0 (_tmp51_);
				_tmp52_ = self->priv->date_combo;
				_tmp53_ = iter;
				gtk_combo_box_set_active_iter ((GtkComboBox*) _tmp52_, &_tmp53_);
				_g_free0 (user_str);
				_g_free0 (format);
			}
		}
	}
	_tmp54_ = self->priv->date_store;
	_tmp55_ = gtk_tree_model_iter_n_children ((GtkTreeModel*) _tmp54_, NULL);
	if (_tmp55_ == 0) {
		const gchar* _tmp56_ = NULL;
		_tmp56_ = _ ("No backups to restore");
		assistant_operation_show_error ((AssistantOperation*) self, _tmp56_, NULL);
	}
	__g_list_free__g_free0_0 (timevals);
}


void assistant_restore_handle_collection_dates (AssistantRestore* self, DejaDupOperationStatus* op, GList* dates) {
	g_return_if_fail (self != NULL);
	ASSISTANT_RESTORE_GET_CLASS (self)->handle_collection_dates (self, op, dates);
}


static void assistant_restore_real_query_finished (AssistantRestore* self, DejaDupOperation* op, gboolean success, gboolean cancelled, const gchar* detail) {
	DejaDupOperation* _tmp0_;
	DejaDupOperationState* _tmp1_ = NULL;
	gboolean _tmp2_;
	g_return_if_fail (op != NULL);
	_tmp0_ = op;
	_tmp1_ = deja_dup_operation_get_state (_tmp0_);
	_deja_dup_operation_state_unref0 (self->op_state);
	self->op_state = _tmp1_;
	_g_object_unref0 (self->query_op);
	self->query_op = NULL;
	_g_object_unref0 (((AssistantOperation*) self)->op);
	((AssistantOperation*) self)->op = NULL;
	_tmp2_ = cancelled;
	if (_tmp2_) {
		assistant_operation_do_close ((AssistantOperation*) self);
	} else {
		gboolean _tmp3_;
		_tmp3_ = success;
		if (_tmp3_) {
			assistant_go_forward ((Assistant*) self);
		}
	}
}


void assistant_restore_query_finished (AssistantRestore* self, DejaDupOperation* op, gboolean success, gboolean cancelled, const gchar* detail) {
	g_return_if_fail (self != NULL);
	ASSISTANT_RESTORE_GET_CLASS (self)->query_finished (self, op, success, cancelled, detail);
}


static gboolean assistant_restore_query_pulse (AssistantRestore* self) {
	gboolean result = FALSE;
	GtkProgressBar* _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->query_progress_bar;
	gtk_progress_bar_pulse (_tmp0_);
	result = TRUE;
	return result;
}


static void assistant_restore_do_query_data_free (gpointer _data) {
	AssistantRestoreDoQueryData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (AssistantRestoreDoQueryData, _data_);
}


void assistant_restore_do_query (AssistantRestore* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	AssistantRestoreDoQueryData* _data_;
	AssistantRestore* _tmp0_;
	_data_ = g_slice_new0 (AssistantRestoreDoQueryData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, assistant_restore_do_query);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, assistant_restore_do_query_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	assistant_restore_do_query_co (_data_);
}


void assistant_restore_do_query_finish (AssistantRestore* self, GAsyncResult* _res_) {
	AssistantRestoreDoQueryData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void _assistant_restore_query_finished_deja_dup_operation_done (DejaDupOperation* _sender, gboolean success, gboolean cancelled, const gchar* detail, gpointer self) {
	assistant_restore_query_finished (self, _sender, success, cancelled, detail);
}


static void __lambda34_ (AssistantRestore* self, DejaDupOperation* o, const gchar* e, const gchar* d) {
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	g_return_if_fail (o != NULL);
	g_return_if_fail (e != NULL);
	_tmp0_ = e;
	_tmp1_ = d;
	assistant_operation_show_error ((AssistantOperation*) self, _tmp0_, _tmp1_);
}


static void ___lambda34__deja_dup_operation_raise_error (DejaDupOperation* _sender, const gchar* errstr, const gchar* detail, gpointer self) {
	__lambda34_ (self, _sender, errstr, detail);
}


static void _assistant_operation_get_passphrase_deja_dup_operation_passphrase_required (DejaDupOperation* _sender, gpointer self) {
	assistant_operation_get_passphrase (self);
}


static void _assistant_restore_handle_collection_dates_deja_dup_operation_status_collection_dates (DejaDupOperationStatus* _sender, GList* dates, gpointer self) {
	assistant_restore_handle_collection_dates (self, _sender, dates);
}


static void _assistant_operation_pause_op_deja_dup_backend_pause_op (DejaDupBackend* _sender, const gchar* header, const gchar* msg, gpointer self) {
	assistant_operation_pause_op (self, _sender, header, msg);
}


static gboolean assistant_restore_do_query_co (AssistantRestoreDoQueryData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	gtk_widget_realize ((GtkWidget*) _data_->self);
	_data_->_tmp0_ = deja_dup_operation_status_new ();
	_g_object_unref0 (_data_->self->query_op);
	_data_->self->query_op = _data_->_tmp0_;
	_data_->_tmp1_ = _data_->self->query_op;
	_data_->_tmp2_ = _g_object_ref0 ((DejaDupOperation*) _data_->_tmp1_);
	_g_object_unref0 (((AssistantOperation*) _data_->self)->op);
	((AssistantOperation*) _data_->self)->op = _data_->_tmp2_;
	_data_->_tmp3_ = ((AssistantOperation*) _data_->self)->op;
	g_signal_connect_object (_data_->_tmp3_, "done", (GCallback) _assistant_restore_query_finished_deja_dup_operation_done, _data_->self, 0);
	_data_->_tmp4_ = ((AssistantOperation*) _data_->self)->op;
	g_signal_connect_object (_data_->_tmp4_, "raise-error", (GCallback) ___lambda34__deja_dup_operation_raise_error, _data_->self, 0);
	_data_->_tmp5_ = ((AssistantOperation*) _data_->self)->op;
	g_signal_connect_object (_data_->_tmp5_, "passphrase-required", (GCallback) _assistant_operation_get_passphrase_deja_dup_operation_passphrase_required, (AssistantOperation*) _data_->self, 0);
	_data_->_tmp6_ = _data_->self->query_op;
	g_signal_connect_object (_data_->_tmp6_, "collection-dates", (GCallback) _assistant_restore_handle_collection_dates_deja_dup_operation_status_collection_dates, _data_->self, 0);
	_data_->_tmp7_ = ((AssistantOperation*) _data_->self)->op;
	_data_->_tmp8_ = deja_dup_operation_get_backend (_data_->_tmp7_);
	_data_->_tmp9_ = _data_->_tmp8_;
	_data_->_tmp10_ = mount_operation_assistant_new ((AssistantOperation*) _data_->self);
	_data_->_tmp11_ = _data_->_tmp10_;
	deja_dup_backend_set_mount_op (_data_->_tmp9_, (GMountOperation*) _data_->_tmp11_);
	_g_object_unref0 (_data_->_tmp11_);
	_data_->_tmp12_ = ((AssistantOperation*) _data_->self)->op;
	_data_->_tmp13_ = deja_dup_operation_get_backend (_data_->_tmp12_);
	_data_->_tmp14_ = _data_->_tmp13_;
	g_signal_connect_object (_data_->_tmp14_, "pause-op", (GCallback) _assistant_operation_pause_op_deja_dup_backend_pause_op, (AssistantOperation*) _data_->self, 0);
	_data_->_tmp15_ = ((AssistantOperation*) _data_->self)->op;
	deja_dup_operation_start (_data_->_tmp15_, TRUE, NULL, NULL);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void ______lambda35_ (AssistantRestore* self, GtkWidget* w) {
	GtkWidget* _tmp0_;
	g_return_if_fail (w != NULL);
	_tmp0_ = w;
	deja_dup_destroy_widget (_tmp0_);
}


static void _______lambda35__gtk_callback (GtkWidget* widget, gpointer self) {
	______lambda35_ (self, widget);
}


static gboolean _assistant_restore_query_pulse_gsource_func (gpointer self) {
	gboolean result;
	result = assistant_restore_query_pulse (self);
	return result;
}


static void assistant_restore_real_do_prepare (AssistantOperation* base, Assistant* assist, GtkWidget* page) {
	AssistantRestore * self;
	Assistant* _tmp0_;
	GtkWidget* _tmp1_;
	guint _tmp2_;
	GtkWidget* _tmp4_;
	GtkWidget* _tmp5_;
	self = (AssistantRestore*) base;
	g_return_if_fail (assist != NULL);
	g_return_if_fail (page != NULL);
	_tmp0_ = assist;
	_tmp1_ = page;
	ASSISTANT_OPERATION_CLASS (assistant_restore_parent_class)->do_prepare (ASSISTANT_OPERATION (self), _tmp0_, _tmp1_);
	_tmp2_ = self->priv->query_timeout_id;
	if (_tmp2_ > ((guint) 0)) {
		guint _tmp3_;
		_tmp3_ = self->priv->query_timeout_id;
		g_source_remove (_tmp3_);
		self->priv->query_timeout_id = (guint) 0;
	}
	_tmp4_ = page;
	_tmp5_ = self->priv->date_page;
	if (_tmp4_ == _tmp5_) {
		gboolean _tmp6_;
		_tmp6_ = self->priv->got_dates;
		if (!_tmp6_) {
			assistant_skip ((Assistant*) self);
		}
	} else {
		GtkWidget* _tmp7_;
		GtkWidget* _tmp8_;
		_tmp7_ = page;
		_tmp8_ = self->priv->restore_dest_page;
		if (_tmp7_ == _tmp8_) {
			GList* _tmp9_;
			GList* _tmp10_;
			_tmp9_ = assistant_restore_get_restore_files (self);
			_tmp10_ = _tmp9_;
			if (_tmp10_ != NULL) {
				assistant_skip ((Assistant*) self);
			}
		} else {
			GtkWidget* _tmp11_;
			GtkWidget* _tmp12_;
			GtkWidget* _tmp13_;
			_tmp11_ = page;
			_tmp12_ = assistant_operation_get_confirm_page ((AssistantOperation*) self);
			_tmp13_ = _tmp12_;
			if (_tmp11_ == _tmp13_) {
				gboolean _tmp14_;
				GList* _tmp22_;
				GList* _tmp23_;
				_tmp14_ = self->priv->got_dates;
				if (_tmp14_) {
					GtkLabel* _tmp15_;
					GtkComboBoxText* _tmp16_;
					const gchar* _tmp17_ = NULL;
					GtkLabel* _tmp18_;
					GtkLabel* _tmp19_;
					_tmp15_ = self->priv->confirm_date;
					_tmp16_ = self->priv->date_combo;
					_tmp17_ = gtk_combo_box_text_get_active_text (_tmp16_);
					gtk_label_set_label (_tmp15_, _tmp17_);
					_tmp18_ = self->priv->confirm_date_label;
					gtk_widget_show ((GtkWidget*) _tmp18_);
					_tmp19_ = self->priv->confirm_date;
					gtk_widget_show ((GtkWidget*) _tmp19_);
				} else {
					GtkLabel* _tmp20_;
					GtkLabel* _tmp21_;
					_tmp20_ = self->priv->confirm_date_label;
					gtk_widget_hide ((GtkWidget*) _tmp20_);
					_tmp21_ = self->priv->confirm_date;
					gtk_widget_hide ((GtkWidget*) _tmp21_);
				}
				_tmp22_ = assistant_restore_get_restore_files (self);
				_tmp23_ = _tmp22_;
				if (_tmp23_ == NULL) {
					const gchar* _tmp24_;
					GtkLabel* _tmp33_;
					GtkLabel* _tmp34_;
					GtkLabel* _tmp35_;
					GtkGrid* _tmp36_;
					_tmp24_ = self->priv->_restore_location;
					if (g_strcmp0 (_tmp24_, "/") == 0) {
						GtkLabel* _tmp25_;
						const gchar* _tmp26_ = NULL;
						_tmp25_ = self->priv->confirm_location;
						_tmp26_ = _ ("Original location");
						gtk_label_set_label (_tmp25_, _tmp26_);
					} else {
						GtkLabel* _tmp27_;
						const gchar* _tmp28_;
						GFile* _tmp29_ = NULL;
						GFile* _tmp30_;
						gchar* _tmp31_ = NULL;
						gchar* _tmp32_;
						_tmp27_ = self->priv->confirm_location;
						_tmp28_ = self->priv->_restore_location;
						_tmp29_ = g_file_new_for_path (_tmp28_);
						_tmp30_ = _tmp29_;
						_tmp31_ = deja_dup_get_file_desc (_tmp30_);
						_tmp32_ = _tmp31_;
						gtk_label_set_label (_tmp27_, _tmp32_);
						_g_free0 (_tmp32_);
						_g_object_unref0 (_tmp30_);
					}
					_tmp33_ = self->priv->confirm_location_label;
					gtk_widget_show ((GtkWidget*) _tmp33_);
					_tmp34_ = self->priv->confirm_location;
					gtk_widget_show ((GtkWidget*) _tmp34_);
					_tmp35_ = self->priv->confirm_files_label;
					gtk_widget_hide ((GtkWidget*) _tmp35_);
					_tmp36_ = self->priv->confirm_files;
					gtk_widget_hide ((GtkWidget*) _tmp36_);
				} else {
					GtkLabel* _tmp37_;
					GList* _tmp38_;
					GList* _tmp39_;
					guint _tmp40_ = 0U;
					const gchar* _tmp41_ = NULL;
					GtkGrid* _tmp42_;
					GList* _tmp43_;
					GList* _tmp44_;
					GtkLabel* _tmp59_;
					GtkLabel* _tmp60_;
					GtkLabel* _tmp61_;
					GtkGrid* _tmp62_;
					_tmp37_ = self->priv->confirm_files_label;
					_tmp38_ = assistant_restore_get_restore_files (self);
					_tmp39_ = _tmp38_;
					_tmp40_ = g_list_length (_tmp39_);
					_tmp41_ = g_dngettext (GETTEXT_PACKAGE, "File to restore", "Files to restore", (gulong) _tmp40_);
					gtk_label_set_label (_tmp37_, _tmp41_);
					_tmp42_ = self->priv->confirm_files;
					gtk_container_foreach ((GtkContainer*) _tmp42_, _______lambda35__gtk_callback, self);
					_tmp43_ = assistant_restore_get_restore_files (self);
					_tmp44_ = _tmp43_;
					{
						GList* f_collection = NULL;
						GList* f_it = NULL;
						f_collection = _tmp44_;
						for (f_it = f_collection; f_it != NULL; f_it = f_it->next) {
							GFile* _tmp45_;
							GFile* f = NULL;
							_tmp45_ = _g_object_ref0 ((GFile*) f_it->data);
							f = _tmp45_;
							{
								GFile* _tmp46_;
								gchar* _tmp47_ = NULL;
								gchar* parse_name;
								const gchar* _tmp48_;
								gchar* _tmp49_ = NULL;
								gchar* _tmp50_;
								GtkLabel* _tmp51_;
								GtkLabel* _tmp52_;
								GtkLabel* _tmp53_;
								GtkLabel* file_label;
								GtkLabel* _tmp54_;
								const gchar* _tmp55_;
								GtkLabel* _tmp56_;
								GtkGrid* _tmp57_;
								GtkLabel* _tmp58_;
								_tmp46_ = f;
								_tmp47_ = g_file_get_parse_name (_tmp46_);
								parse_name = _tmp47_;
								_tmp48_ = parse_name;
								_tmp49_ = g_path_get_basename (_tmp48_);
								_tmp50_ = _tmp49_;
								_tmp51_ = (GtkLabel*) gtk_label_new (_tmp50_);
								_tmp52_ = g_object_ref_sink (_tmp51_);
								_tmp53_ = _tmp52_;
								_g_free0 (_tmp50_);
								file_label = _tmp53_;
								_tmp54_ = file_label;
								_tmp55_ = parse_name;
								gtk_widget_set_tooltip_text ((GtkWidget*) _tmp54_, _tmp55_);
								_tmp56_ = file_label;
								g_object_set ((GObject*) _tmp56_, "xalign", 0.0f, NULL);
								_tmp57_ = self->priv->confirm_files;
								_tmp58_ = file_label;
								gtk_container_add ((GtkContainer*) _tmp57_, (GtkWidget*) _tmp58_);
								_g_object_unref0 (file_label);
								_g_free0 (parse_name);
								_g_object_unref0 (f);
							}
						}
					}
					_tmp59_ = self->priv->confirm_location_label;
					gtk_widget_hide ((GtkWidget*) _tmp59_);
					_tmp60_ = self->priv->confirm_location;
					gtk_widget_hide ((GtkWidget*) _tmp60_);
					_tmp61_ = self->priv->confirm_files_label;
					gtk_widget_show ((GtkWidget*) _tmp61_);
					_tmp62_ = self->priv->confirm_files;
					gtk_widget_show_all ((GtkWidget*) _tmp62_);
				}
			} else {
				GtkWidget* _tmp63_;
				GtkWidget* _tmp64_;
				GtkWidget* _tmp65_;
				_tmp63_ = page;
				_tmp64_ = assistant_operation_get_summary_page ((AssistantOperation*) self);
				_tmp65_ = _tmp64_;
				if (_tmp63_ == _tmp65_) {
					gboolean _tmp66_;
					gboolean _tmp67_;
					_tmp66_ = assistant_operation_get_error_occurred ((AssistantOperation*) self);
					_tmp67_ = _tmp66_;
					if (_tmp67_) {
						GtkWidget* _tmp68_;
						const gchar* _tmp69_ = NULL;
						_tmp68_ = page;
						_tmp69_ = _ ("Restore Failed");
						assistant_set_page_title ((Assistant*) self, _tmp68_, _tmp69_);
					} else {
						GtkWidget* _tmp70_;
						const gchar* _tmp71_ = NULL;
						GtkWidget* _tmp72_;
						gboolean _tmp73_ = FALSE;
						_tmp70_ = page;
						_tmp71_ = _ ("Restore Finished");
						assistant_set_page_title ((Assistant*) self, _tmp70_, _tmp71_);
						_tmp72_ = ((AssistantOperation*) self)->detail_widget;
						_tmp73_ = gtk_widget_get_visible (_tmp72_);
						if (!_tmp73_) {
							GList* _tmp74_;
							GList* _tmp75_;
							_tmp74_ = assistant_restore_get_restore_files (self);
							_tmp75_ = _tmp74_;
							if (_tmp75_ == NULL) {
								GtkLabel* _tmp76_;
								const gchar* _tmp77_ = NULL;
								_tmp76_ = ((AssistantOperation*) self)->summary_label;
								_tmp77_ = _ ("Your files were successfully restored.");
								gtk_label_set_label (_tmp76_, _tmp77_);
							} else {
								GtkLabel* _tmp78_;
								GList* _tmp79_;
								GList* _tmp80_;
								guint _tmp81_ = 0U;
								const gchar* _tmp82_ = NULL;
								_tmp78_ = ((AssistantOperation*) self)->summary_label;
								_tmp79_ = assistant_restore_get_restore_files (self);
								_tmp80_ = _tmp79_;
								_tmp81_ = g_list_length (_tmp80_);
								_tmp82_ = g_dngettext (GETTEXT_PACKAGE, "Your file was successfully restored.", "Your files were successfully restored.", (gulong) _tmp81_);
								gtk_label_set_label (_tmp78_, _tmp82_);
							}
						}
					}
				} else {
					GtkWidget* _tmp83_;
					GtkWidget* _tmp84_;
					GtkWidget* _tmp85_;
					_tmp83_ = page;
					_tmp84_ = assistant_operation_get_progress_page ((AssistantOperation*) self);
					_tmp85_ = _tmp84_;
					if (_tmp83_ == _tmp85_) {
						GtkWidget* _tmp86_;
						const gchar* _tmp87_ = NULL;
						_tmp86_ = page;
						_tmp87_ = _ ("Restoring…");
						assistant_set_page_title ((Assistant*) self, _tmp86_, _tmp87_);
					} else {
						GtkWidget* _tmp88_;
						GtkWidget* _tmp89_;
						_tmp88_ = page;
						_tmp89_ = self->priv->query_progress_page;
						if (_tmp88_ == _tmp89_) {
							gboolean _tmp90_;
							gboolean _tmp91_;
							_tmp90_ = assistant_get_last_op_was_back ((Assistant*) self);
							_tmp91_ = _tmp90_;
							if (_tmp91_) {
								assistant_skip ((Assistant*) self);
							} else {
								GtkProgressBar* _tmp92_;
								guint _tmp93_ = 0U;
								gboolean _tmp94_ = FALSE;
								DejaDupOperationStatus* _tmp95_;
								gboolean _tmp99_;
								_tmp92_ = self->priv->query_progress_bar;
								gtk_progress_bar_set_fraction (_tmp92_, (gdouble) 0);
								_tmp93_ = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 250, _assistant_restore_query_pulse_gsource_func, g_object_ref (self), g_object_unref);
								self->priv->query_timeout_id = _tmp93_;
								_tmp95_ = self->query_op;
								if (_tmp95_ != NULL) {
									DejaDupOperationStatus* _tmp96_;
									gboolean _tmp97_;
									gboolean _tmp98_;
									_tmp96_ = self->query_op;
									_tmp97_ = deja_dup_operation_get_needs_password ((DejaDupOperation*) _tmp96_);
									_tmp98_ = _tmp97_;
									_tmp94_ = _tmp98_;
								} else {
									_tmp94_ = FALSE;
								}
								_tmp99_ = _tmp94_;
								if (_tmp99_) {
									assistant_operation_provide_password ((AssistantOperation*) self);
								} else {
									DejaDupOperationStatus* _tmp100_;
									_tmp100_ = self->query_op;
									if (_tmp100_ == NULL) {
										assistant_restore_do_query (self, NULL, NULL);
									}
								}
							}
						}
					}
				}
			}
		}
	}
}


static void assistant_restore_real_do_close (AssistantOperation* base) {
	AssistantRestore * self;
	guint _tmp0_;
	self = (AssistantRestore*) base;
	_tmp0_ = self->priv->query_timeout_id;
	if (_tmp0_ > ((guint) 0)) {
		guint _tmp1_;
		_tmp1_ = self->priv->query_timeout_id;
		g_source_remove (_tmp1_);
		self->priv->query_timeout_id = (guint) 0;
	}
	ASSISTANT_OPERATION_CLASS (assistant_restore_parent_class)->do_close (ASSISTANT_OPERATION (self));
}


AssistantRestore* assistant_restore_construct (GType object_type) {
	AssistantRestore * self = NULL;
	self = (AssistantRestore*) assistant_operation_construct (object_type);
	return self;
}


AssistantRestore* assistant_restore_new (void) {
	return assistant_restore_construct (TYPE_ASSISTANT_RESTORE);
}


const gchar* assistant_restore_get_restore_location (AssistantRestore* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_restore_location;
	result = _tmp0_;
	return result;
}


void assistant_restore_set_restore_location (AssistantRestore* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_restore_location);
	self->priv->_restore_location = _tmp1_;
	g_object_notify ((GObject *) self, "restore-location");
}


GList* assistant_restore_get_restore_files (AssistantRestore* self) {
	GList* result;
	GList* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_restore_files;
	result = _tmp0_;
	return result;
}


void assistant_restore_set_restore_files (AssistantRestore* self, GList* value) {
	GList* _tmp0_;
	GList* _tmp3_;
	GList* _tmp4_ = NULL;
	GList* _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->_restore_files;
	{
		GList* f_collection = NULL;
		GList* f_it = NULL;
		f_collection = _tmp0_;
		for (f_it = f_collection; f_it != NULL; f_it = f_it->next) {
			GFile* _tmp1_;
			GFile* f = NULL;
			_tmp1_ = _g_object_ref0 ((GFile*) f_it->data);
			f = _tmp1_;
			{
				GFile* _tmp2_;
				_tmp2_ = f;
				g_object_unref ((GObject*) _tmp2_);
				_g_object_unref0 (f);
			}
		}
	}
	_tmp3_ = value;
	_tmp4_ = g_list_copy (_tmp3_);
	__g_list_free__g_object_unref0_0 (self->_restore_files);
	self->_restore_files = _tmp4_;
	_tmp5_ = self->_restore_files;
	{
		GList* f_collection = NULL;
		GList* f_it = NULL;
		f_collection = _tmp5_;
		for (f_it = f_collection; f_it != NULL; f_it = f_it->next) {
			GFile* _tmp6_;
			GFile* f = NULL;
			_tmp6_ = _g_object_ref0 ((GFile*) f_it->data);
			f = _tmp6_;
			{
				GFile* _tmp7_;
				_tmp7_ = f;
				g_object_ref ((GObject*) _tmp7_);
				_g_object_unref0 (f);
			}
		}
	}
	g_object_notify ((GObject *) self, "restore-files");
}


static GObject * assistant_restore_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	AssistantRestore * self;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	parent_class = G_OBJECT_CLASS (assistant_restore_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = ASSISTANT_RESTORE (obj);
	_tmp0_ = _ ("Restore");
	gtk_window_set_title ((GtkWindow*) self, _tmp0_);
	_tmp1_ = _ ("_Restore");
	assistant_set_apply_text ((Assistant*) self, _tmp1_);
	return obj;
}


static void assistant_restore_class_init (AssistantRestoreClass * klass) {
	assistant_restore_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (AssistantRestorePrivate));
	ASSISTANT_OPERATION_CLASS (klass)->add_setup_pages = assistant_restore_real_add_setup_pages;
	ASSISTANT_OPERATION_CLASS (klass)->add_custom_config_pages = assistant_restore_real_add_custom_config_pages;
	ASSISTANT_OPERATION_CLASS (klass)->make_confirm_page = assistant_restore_real_make_confirm_page;
	ASSISTANT_OPERATION_CLASS (klass)->create_op = assistant_restore_real_create_op;
	ASSISTANT_OPERATION_CLASS (klass)->get_progress_file_prefix = assistant_restore_real_get_progress_file_prefix;
	ASSISTANT_RESTORE_CLASS (klass)->handle_collection_dates = assistant_restore_real_handle_collection_dates;
	ASSISTANT_RESTORE_CLASS (klass)->query_finished = assistant_restore_real_query_finished;
	ASSISTANT_OPERATION_CLASS (klass)->do_prepare = assistant_restore_real_do_prepare;
	ASSISTANT_OPERATION_CLASS (klass)->do_close = assistant_restore_real_do_close;
	G_OBJECT_CLASS (klass)->get_property = _vala_assistant_restore_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_assistant_restore_set_property;
	G_OBJECT_CLASS (klass)->constructor = assistant_restore_constructor;
	G_OBJECT_CLASS (klass)->finalize = assistant_restore_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ASSISTANT_RESTORE_RESTORE_LOCATION, g_param_spec_string ("restore-location", "restore-location", "restore-location", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ASSISTANT_RESTORE_RESTORE_FILES, g_param_spec_pointer ("restore-files", "restore-files", "restore-files", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void assistant_restore_instance_init (AssistantRestore * self) {
	gchar* _tmp0_;
	self->priv = ASSISTANT_RESTORE_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("/");
	self->priv->_restore_location = _tmp0_;
}


static void assistant_restore_finalize (GObject* obj) {
	AssistantRestore * self;
	self = ASSISTANT_RESTORE (obj);
	_g_free0 (self->priv->_restore_location);
	__g_list_free__g_object_unref0_0 (self->_restore_files);
	_g_object_unref0 (self->query_op);
	_deja_dup_operation_state_unref0 (self->op_state);
	_g_object_unref0 (self->priv->query_progress_bar);
	_g_object_unref0 (self->priv->date_combo);
	_g_object_unref0 (self->priv->date_store);
	_g_object_unref0 (self->priv->cust_box);
	_g_object_unref0 (self->priv->cust_button);
	_g_object_unref0 (self->priv->confirm_table);
	_g_object_unref0 (self->priv->confirm_location_label);
	_g_object_unref0 (self->priv->confirm_location);
	_g_object_unref0 (self->priv->confirm_date_label);
	_g_object_unref0 (self->priv->confirm_date);
	_g_object_unref0 (self->priv->confirm_files_label);
	_g_object_unref0 (self->priv->confirm_files);
	_g_object_unref0 (self->priv->query_progress_page);
	_g_object_unref0 (self->priv->date_page);
	_g_object_unref0 (self->priv->restore_dest_page);
	G_OBJECT_CLASS (assistant_restore_parent_class)->finalize (obj);
}


GType assistant_restore_get_type (void) {
	static volatile gsize assistant_restore_type_id__volatile = 0;
	if (g_once_init_enter (&assistant_restore_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AssistantRestoreClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) assistant_restore_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AssistantRestore), 0, (GInstanceInitFunc) assistant_restore_instance_init, NULL };
		GType assistant_restore_type_id;
		assistant_restore_type_id = g_type_register_static (TYPE_ASSISTANT_OPERATION, "AssistantRestore", &g_define_type_info, 0);
		g_once_init_leave (&assistant_restore_type_id__volatile, assistant_restore_type_id);
	}
	return assistant_restore_type_id__volatile;
}


static void _vala_assistant_restore_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	AssistantRestore * self;
	self = ASSISTANT_RESTORE (object);
	switch (property_id) {
		case ASSISTANT_RESTORE_RESTORE_LOCATION:
		g_value_set_string (value, assistant_restore_get_restore_location (self));
		break;
		case ASSISTANT_RESTORE_RESTORE_FILES:
		g_value_set_pointer (value, assistant_restore_get_restore_files (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_assistant_restore_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	AssistantRestore * self;
	self = ASSISTANT_RESTORE (object);
	switch (property_id) {
		case ASSISTANT_RESTORE_RESTORE_LOCATION:
		assistant_restore_set_restore_location (self, g_value_get_string (value));
		break;
		case ASSISTANT_RESTORE_RESTORE_FILES:
		assistant_restore_set_restore_files (self, g_value_get_pointer (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



