/* libduplicity.vapi generated by valac-0.16 0.16.1, do not modify. */

[CCode (cheader_filename = "DuplicityPlugin.h")]
public class DuplicityPlugin : DejaDup.ToolPlugin {
	public DuplicityPlugin ();
	public override DejaDup.ToolJob create_job () throws GLib.Error;
}
[CCode (cheader_filename = "DuplicityPlugin.h")]
[ModuleInit]
public static void peas_register_types (GLib.TypeModule module);
